#!/usr/bin/env node
/**
 * PreToolUse hook (Edit|MultiEdit|Write): blocks edits to generated,
 * stateful, or secret files. Fail-open: any internal error => allow.
 * Emits a PreToolUse permissionDecision on stdout and always exits 0.
 *
 * Protected:
 *  - web/src/routeTree.gen.ts        (generated by TanStack Router)
 *  - *.tfstate / *.tfstate.backup    (committed Terraform state)
 *  - tracked supabase/migrations/*.sql (applied migrations are immutable)
 *  - .env files (except .env.example/.template/.sample)
 *  - web/src/styles.css              (ask - theme tokens live here)
 */
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

function decide(decision, reason) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: decision,
        permissionDecisionReason: reason,
      },
    }),
  );
  process.exit(0);
}

try {
  const input = JSON.parse(readFileSync(0, "utf8"));
  const filePath = input?.tool_input?.file_path;
  if (!filePath) process.exit(0);

  // Normalize for matching (Windows backslashes, case-insensitive FS).
  const p = String(filePath).replace(/\\/g, "/").toLowerCase();
  const base = p.split("/").pop() ?? "";
  const root = process.env.CLAUDE_PROJECT_DIR || process.cwd();

  if (base === "routetree.gen.ts") {
    decide(
      "deny",
      "routeTree.gen.ts is generated by TanStack Router and must never be hand-edited. Add/rename route files under web/src/routes/ and let the dev server or `npm run build` regenerate it.",
    );
  }

  if (p.endsWith(".tfstate") || p.endsWith(".tfstate.backup")) {
    decide(
      "deny",
      "Terraform state files are committed on purpose and must never be modified by hand.",
    );
  }

  if (/\/supabase\/migrations\/[^/]+\.sql$/.test(p)) {
    let tracked = false;
    try {
      execFileSync("git", ["ls-files", "--error-unmatch", "--", filePath], {
        cwd: root,
        stdio: "ignore",
        timeout: 5000,
      });
      tracked = true;
    } catch {
      tracked = false; // untracked (new) migration, or git unavailable -> allow
    }
    if (tracked) {
      decide(
        "deny",
        "This migration is tracked in git and may already be applied - applied migrations are immutable. Create a NEW timestamped migration instead. If it redefines a SQL function, rebuild from the NEWEST migration that defines it (see supabase/CLAUDE.md).",
      );
    }
    process.exit(0);
  }

  if (
    base === ".env" ||
    (base.startsWith(".env.") &&
      base !== ".env.example" &&
      base !== ".env.template" &&
      base !== ".env.sample")
  ) {
    decide(
      "deny",
      "Editing .env files is blocked - they contain real secrets. Ask the user to change env values, or update .env.example instead.",
    );
  }

  if (p.endsWith("/web/src/styles.css")) {
    decide(
      "ask",
      "web/src/styles.css defines the Tailwind theme tokens. Confirm this change is intentional - components should consume theme tokens (bg-primary, text-primary, blue-600), not introduce raw hex values.",
    );
  }

  process.exit(0);
} catch {
  process.exit(0); // fail open - never block edits because the hook broke
}
