// Tech-debt cleanup (slice 3b follow-up):
//
// This file used to contain the legacy permissions_json template system —
// 700 lines of templates, helpers, and dependency rules per project member
// role. After the project_shares refactor (slice 2 + 3b), authorization
// runs through `ProjectAuthorizationService.assertRole` against the
// project_shares.role hierarchy + capabilities JSONB.
//
// What remains here is just the type surface that frontend & legacy
// controller endpoints still expect — the synthesized permissions object
// generated by `ProjectsService.synthesizePermissionsFromRole` matches
// this shape, and `assertProjectPermission` accepts the same path strings
// (mapped to a min-role internally via `permissionToMinRole`).

export type ProjectPermissions = {
  access: {
    roadmap: boolean;
    work_items: boolean;
    team: boolean;
    time: boolean;
    chat: boolean;
    resources: boolean;
    project_settings: boolean;
  };
  roadmap: {
    edit: boolean;
    comment: boolean;
    promote: boolean;
    assign: boolean;
    edit_metadata: boolean;
    view_internal: boolean;
    create_tasks: boolean;
    edit_tasks: boolean;
    share: boolean;
    export: boolean;
    dev_mode: boolean;
  };
  members: {
    view: boolean;
    manage: boolean;
    edit_permissions: boolean;
  };
  project: {
    settings: boolean;
    edit_content: boolean;
    view_internal_content: boolean;
  };
  time: {
    view: boolean;
    view_financial: boolean;
    log: boolean;
    edit_own: boolean;
    edit_team: boolean;
    approve: boolean;
    manage_rates: boolean;
    delete_logs: boolean;
  };
  chat: {
    view_channels: boolean;
    send_messages: boolean;
    create_channels: boolean;
    manage_channels: boolean;
    view_internal_channels: boolean;
    mention_members: boolean;
    share_files: boolean;
    start_dm: boolean;
    send_dm: boolean;
    message_clients: boolean;
    message_consultants: boolean;
    message_freelancers: boolean;
  };
  resources: {
    view: boolean;
    upload: boolean;
    delete: boolean;
  };
  logs: {
    view: boolean;
    view_sensitive: boolean;
  };
};

export type PermissionPath =
  | 'access.roadmap'
  | 'access.work_items'
  | 'access.team'
  | 'access.time'
  | 'access.chat'
  | 'access.resources'
  | 'access.project_settings'
  | 'roadmap.edit'
  | 'roadmap.comment'
  | 'roadmap.promote'
  | 'roadmap.assign'
  | 'roadmap.edit_metadata'
  | 'roadmap.view_internal'
  | 'roadmap.create_tasks'
  | 'roadmap.edit_tasks'
  | 'roadmap.share'
  | 'roadmap.export'
  | 'roadmap.dev_mode'
  | 'members.view'
  | 'members.manage'
  | 'members.edit_permissions'
  | 'project.settings'
  | 'project.edit_content'
  | 'project.view_internal_content'
  | 'time.view'
  | 'time.view_financial'
  | 'time.log'
  | 'time.edit_own'
  | 'time.edit_team'
  | 'time.approve'
  | 'time.manage_rates'
  | 'time.delete_logs'
  | 'chat.view_channels'
  | 'chat.send_messages'
  | 'chat.create_channels'
  | 'chat.manage_channels'
  | 'chat.view_internal_channels'
  | 'chat.mention_members'
  | 'chat.share_files'
  | 'chat.start_dm'
  | 'chat.send_dm'
  | 'chat.message_clients'
  | 'chat.message_consultants'
  | 'chat.message_freelancers'
  | 'resources.view'
  | 'resources.upload'
  | 'resources.delete'
  | 'logs.view'
  | 'logs.view_sensitive';
