
"""Deterministic materialization of a confirmed pending plan into
`RoadmapOperation` list — no LLM inference.

Confirming a pending plan is a mechanical transform: the plan was already
generated by the LLM (proposal turn) and approved verbatim by the user.
Re-asking the LLM to emit `add_epic`/`add_feature`/`add_task` ops for the
approved hierarchy is wasted inference and, for any plan larger than
~30 ops, truncates at the output-token ceiling (see logs.txt:1009,
`PROVIDER_FAILURE(planner_output_truncated)` for a 4×3×3 roadmap).

This module walks `PendingPlan.proposed_hierarchy` and returns the
operations directly. The caller short-circuits the edit LLM turn when
the synthesizer succeeds, and falls back to the LLM path when synthesis
refuses (e.g. plan requires anchor resolution against an existing
roadmap — v1 scope intentionally only handles pure-create plans).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from app.core.contracts.operations import RoadmapOperation
from app.core.contracts.sessions import (
    ActorContext,
    PendingPlan,
    ProposedEpic,
    ProposedFeature,
    ProposedTask,
)
from app.core.tools.registry import TASK_STATUS_VALUES


_FIRST_PERSON_TOKENS: frozenset[str] = frozenset(
    {'me', 'myself', 'self', 'current user', 'the current user', 'i'}
)


@dataclass
class SynthesisResult:
    operations: list[RoadmapOperation] = field(default_factory=list)
    assistant_message: str = ''
    epics_count: int = 0
    features_count: int = 0
    tasks_count: int = 0
    statuses_dropped: int = 0
    assignees_resolved: int = 0
    assignees_dropped: int = 0
    synthesis_skipped_reason: str | None = None


def synthesize_operations_from_pending_plan(
    pending_plan: PendingPlan,
    *,
    actor_context: ActorContext | None = None,
) -> SynthesisResult:
    """Build a `RoadmapOperation` list for a confirmed plan.

    Returns `SynthesisResult` with:
      - `operations`: the ordered op list (empty on skip).
      - `assistant_message`: a one-liner summary ("Staged N epics, M features, K tasks").
      - `synthesis_skipped_reason`: non-None if the caller should fall back to
        the LLM path. Reasons: `'empty_hierarchy'`, `'anchor_resolution_needed'`.

    v1 handles pure-create plans (no `target_epic_title` / `target_feature_title`).
    Anchor-heavy plans fall back to the LLM lane, which is acceptable today —
    the truncation we observed (logs.txt:1009) was on an empty roadmap with an
    all-create plan.
    """
    result = SynthesisResult()
    hierarchy = pending_plan.proposed_hierarchy
    if not hierarchy:
        result.synthesis_skipped_reason = 'empty_hierarchy'
        return result
    if _has_any_anchor(hierarchy):
        result.synthesis_skipped_reason = 'anchor_resolution_needed'
        return result

    actor_id = (
        actor_context.actor_id.strip()
        if actor_context is not None and isinstance(actor_context.actor_id, str)
        else ''
    )

    operations: list[RoadmapOperation] = []
    for epic_index, epic in enumerate(hierarchy):
        epic_temp_id = f'epic_{epic_index}'
        epic_data: dict[str, Any] = {'title': epic.title}
        if _non_empty(epic.description):
            epic_data['description'] = epic.description
        operations.append(
            RoadmapOperation(
                op='add_epic',
                temp_id=epic_temp_id,
                data=epic_data,
            )
        )
        result.epics_count += 1
        for feature_index, feature in enumerate(epic.features):
            feature_temp_id = f'feature_{epic_index}_{feature_index}'
            feature_data: dict[str, Any] = {'title': feature.title}
            if _non_empty(feature.description):
                feature_data['description'] = feature.description
            operations.append(
                RoadmapOperation(
                    op='add_feature',
                    temp_id=feature_temp_id,
                    parent_ref=epic_temp_id,
                    data=feature_data,
                )
            )
            result.features_count += 1
            for task_index, task in enumerate(feature.tasks):
                task_temp_id = (
                    f'task_{epic_index}_{feature_index}_{task_index}'
                )
                task_data: dict[str, Any] = {'title': task.title}
                if _non_empty(task.description):
                    task_data['description'] = task.description
                mapped_status = _clamp_status(task.status, TASK_STATUS_VALUES)
                if mapped_status is None and _non_empty(task.status):
                    result.statuses_dropped += 1
                elif mapped_status is not None:
                    task_data['status'] = mapped_status
                resolved_assignee = _resolve_assignee(task.assignee_label, actor_id)
                if resolved_assignee is None and _non_empty(task.assignee_label):
                    result.assignees_dropped += 1
                elif resolved_assignee is not None:
                    task_data['assignee_id'] = resolved_assignee
                    result.assignees_resolved += 1
                operations.append(
                    RoadmapOperation(
                        op='add_task',
                        temp_id=task_temp_id,
                        parent_ref=feature_temp_id,
                        data=task_data,
                    )
                )
                result.tasks_count += 1

    result.operations = operations
    result.assistant_message = _format_summary_message(
        epics=result.epics_count,
        features=result.features_count,
        tasks=result.tasks_count,
    )
    return result


def _has_any_anchor(hierarchy: list[ProposedEpic]) -> bool:
    for epic in hierarchy:
        for feature in epic.features:
            if _non_empty(feature.target_epic_title):
                return True
            for task in feature.tasks:
                if _non_empty(task.target_feature_title):
                    return True
    return False


def _non_empty(value: str | None) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _clamp_status(value: str | None, allowed: list[str]) -> str | None:
    if not _non_empty(value):
        return None
    normalized = str(value).strip()
    if normalized in allowed:
        return normalized
    lowered = normalized.lower().replace('-', '_').replace(' ', '_')
    if lowered in allowed:
        return lowered
    return None


def _resolve_assignee(label: str | None, actor_id: str) -> str | None:
    if not _non_empty(label):
        return None
    normalized = str(label).strip().lower()
    if normalized in _FIRST_PERSON_TOKENS:
        return actor_id or None
    return None


def _format_summary_message(*, epics: int, features: int, tasks: int) -> str:
    parts: list[str] = []
    if epics:
        parts.append(f'{epics} {"epic" if epics == 1 else "epics"}')
    if features:
        parts.append(f'{features} {"feature" if features == 1 else "features"}')
    if tasks:
        parts.append(f'{tasks} {"task" if tasks == 1 else "tasks"}')
    if not parts:
        return 'Staged the confirmed plan.'
    return f'Staged {", ".join(parts)} from the confirmed plan.'


__all__ = [
    'SynthesisResult',
    'synthesize_operations_from_pending_plan',
]
