export interface Country {
	code: string;
	name: string;
	zipLength?: number;
	zipPattern?: string;
}

export const COUNTRIES: Country[] = [
	{ code: "AF", name: "Afghanistan" },
	{ code: "AL", name: "Albania" },
	{ code: "DZ", name: "Algeria" },
	{ code: "AD", name: "Andorra" },
	{ code: "AO", name: "Angola" },
	{ code: "AG", name: "Antigua and Barbuda" },
	{ code: "AR", name: "Argentina", zipLength: 8 },
	{ code: "AM", name: "Armenia" },
	{ code: "AU", name: "Australia", zipLength: 4 },
	{ code: "AT", name: "Austria", zipLength: 4 },
	{ code: "AZ", name: "Azerbaijan" },
	{ code: "BS", name: "Bahamas" },
	{ code: "BH", name: "Bahrain" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "BB", name: "Barbados" },
	{ code: "BY", name: "Belarus" },
	{ code: "BE", name: "Belgium", zipLength: 4 },
	{ code: "BZ", name: "Belize" },
	{ code: "BJ", name: "Benin" },
	{ code: "BT", name: "Bhutan" },
	{ code: "BO", name: "Bolivia" },
	{ code: "BA", name: "Bosnia and Herzegovina" },
	{ code: "BW", name: "Botswana" },
	{ code: "BR", name: "Brazil", zipLength: 8 },
	{ code: "BN", name: "Brunei" },
	{ code: "BG", name: "Bulgaria" },
	{ code: "BF", name: "Burkina Faso" },
	{ code: "BI", name: "Burundi" },
	{ code: "CV", name: "Cabo Verde" },
	{ code: "KH", name: "Cambodia" },
	{ code: "CM", name: "Cameroon" },
	{ code: "CA", name: "Canada", zipLength: 6 },
	{ code: "CF", name: "Central African Republic" },
	{ code: "TD", name: "Chad" },
	{ code: "CL", name: "Chile" },
	{ code: "CN", name: "China", zipLength: 6 },
	{ code: "CO", name: "Colombia" },
	{ code: "KM", name: "Comoros" },
	{ code: "CG", name: "Congo" },
	{ code: "CR", name: "Costa Rica" },
	{ code: "HR", name: "Croatia" },
	{ code: "CU", name: "Cuba" },
	{ code: "CY", name: "Cyprus" },
	{ code: "CZ", name: "Czech Republic", zipLength: 5 },
	{ code: "DK", name: "Denmark", zipLength: 4 },
	{ code: "DJ", name: "Djibouti" },
	{ code: "DM", name: "Dominica" },
	{ code: "DO", name: "Dominican Republic" },
	{ code: "EC", name: "Ecuador" },
	{ code: "EG", name: "Egypt" },
	{ code: "SV", name: "El Salvador" },
	{ code: "GQ", name: "Equatorial Guinea" },
	{ code: "ER", name: "Eritrea" },
	{ code: "EE", name: "Estonia", zipLength: 5 },
	{ code: "SZ", name: "Eswatini" },
	{ code: "ET", name: "Ethiopia" },
	{ code: "FJ", name: "Fiji" },
	{ code: "FI", name: "Finland", zipLength: 5 },
	{ code: "FR", name: "France", zipLength: 5 },
	{ code: "GA", name: "Gabon" },
	{ code: "GM", name: "Gambia" },
	{ code: "GE", name: "Georgia" },
	{ code: "DE", name: "Germany", zipLength: 5 },
	{ code: "GH", name: "Ghana" },
	{ code: "GR", name: "Greece", zipLength: 5 },
	{ code: "GD", name: "Grenada" },
	{ code: "GT", name: "Guatemala" },
	{ code: "GN", name: "Guinea" },
	{ code: "GW", name: "Guinea-Bissau" },
	{ code: "GY", name: "Guyana" },
	{ code: "HT", name: "Haiti" },
	{ code: "HN", name: "Honduras" },
	{ code: "HU", name: "Hungary", zipLength: 4 },
	{ code: "IS", name: "Iceland" },
	{ code: "IN", name: "India", zipLength: 6 },
	{ code: "ID", name: "Indonesia", zipLength: 5 },
	{ code: "IR", name: "Iran" },
	{ code: "IQ", name: "Iraq" },
	{ code: "IE", name: "Ireland", zipLength: 7 },
	{ code: "IL", name: "Israel", zipLength: 7 },
	{ code: "IT", name: "Italy", zipLength: 5 },
	{ code: "JM", name: "Jamaica" },
	{ code: "JP", name: "Japan", zipLength: 7 },
	{ code: "JO", name: "Jordan" },
	{ code: "KZ", name: "Kazakhstan" },
	{ code: "KE", name: "Kenya" },
	{ code: "KI", name: "Kiribati" },
	{ code: "KP", name: "Korea (North)" },
	{ code: "KR", name: "Korea (South)", zipLength: 5 },
	{ code: "KW", name: "Kuwait" },
	{ code: "KG", name: "Kyrgyzstan" },
	{ code: "LA", name: "Laos" },
	{ code: "LV", name: "Latvia" },
	{ code: "LB", name: "Lebanon" },
	{ code: "LS", name: "Lesotho" },
	{ code: "LR", name: "Liberia" },
	{ code: "LY", name: "Libya" },
	{ code: "LI", name: "Liechtenstein" },
	{ code: "LT", name: "Lithuania" },
	{ code: "LU", name: "Luxembourg" },
	{ code: "MG", name: "Madagascar" },
	{ code: "MW", name: "Malawi" },
	{ code: "MY", name: "Malaysia", zipLength: 5 },
	{ code: "MV", name: "Maldives" },
	{ code: "ML", name: "Mali" },
	{ code: "MT", name: "Malta" },
	{ code: "MH", name: "Marshall Islands" },
	{ code: "MR", name: "Mauritania" },
	{ code: "MU", name: "Mauritius" },
	{ code: "MX", name: "Mexico", zipLength: 5 },
	{ code: "FM", name: "Micronesia" },
	{ code: "MD", name: "Moldova" },
	{ code: "MC", name: "Monaco" },
	{ code: "MN", name: "Mongolia" },
	{ code: "ME", name: "Montenegro" },
	{ code: "MA", name: "Morocco" },
	{ code: "MZ", name: "Mozambique" },
	{ code: "MM", name: "Myanmar" },
	{ code: "NA", name: "Namibia" },
	{ code: "NR", name: "Nauru" },
	{ code: "NP", name: "Nepal" },
	{ code: "NL", name: "Netherlands", zipLength: 6 },
	{ code: "NZ", name: "New Zealand", zipLength: 4 },
	{ code: "NI", name: "Nicaragua" },
	{ code: "NE", name: "Niger" },
	{ code: "NG", name: "Nigeria" },
	{ code: "MK", name: "North Macedonia" },
	{ code: "NO", name: "Norway", zipLength: 4 },
	{ code: "OM", name: "Oman" },
	{ code: "PK", name: "Pakistan", zipLength: 5 },
	{ code: "PW", name: "Palau" },
	{ code: "PA", name: "Panama" },
	{ code: "PG", name: "Papua New Guinea" },
	{ code: "PY", name: "Paraguay" },
	{ code: "PE", name: "Peru" },
	{ code: "PH", name: "Philippines", zipLength: 4 },
	{ code: "PL", name: "Poland", zipLength: 6 },
	{ code: "PT", name: "Portugal", zipLength: 7 },
	{ code: "QA", name: "Qatar" },
	{ code: "RO", name: "Romania" },
	{ code: "RU", name: "Russia" },
	{ code: "RW", name: "Rwanda" },
	{ code: "KN", name: "Saint Kitts and Nevis" },
	{ code: "LC", name: "Saint Lucia" },
	{ code: "VC", name: "Saint Vincent and the Grenadines" },
	{ code: "WS", name: "Samoa" },
	{ code: "SM", name: "San Marino" },
	{ code: "ST", name: "Sao Tome and Principe" },
	{ code: "SA", name: "Saudi Arabia", zipLength: 5 },
	{ code: "SN", name: "Senegal" },
	{ code: "RS", name: "Serbia" },
	{ code: "SC", name: "Seychelles" },
	{ code: "SL", name: "Sierra Leone" },
	{ code: "SG", name: "Singapore", zipLength: 6 },
	{ code: "SK", name: "Slovakia", zipLength: 5 },
	{ code: "SI", name: "Slovenia" },
	{ code: "SB", name: "Solomon Islands" },
	{ code: "SO", name: "Somalia" },
	{ code: "ZA", name: "South Africa", zipLength: 4 },
	{ code: "SS", name: "South Sudan" },
	{ code: "ES", name: "Spain", zipLength: 5 },
	{ code: "LK", name: "Sri Lanka" },
	{ code: "SD", name: "Sudan" },
	{ code: "SR", name: "Suriname" },
	{ code: "SE", name: "Sweden", zipLength: 5 },
	{ code: "CH", name: "Switzerland", zipLength: 4 },
	{ code: "SY", name: "Syria" },
	{ code: "TW", name: "Taiwan" },
	{ code: "TJ", name: "Tajikistan" },
	{ code: "TZ", name: "Tanzania" },
	{ code: "TH", name: "Thailand", zipLength: 5 },
	{ code: "TL", name: "Timor-Leste" },
	{ code: "TG", name: "Togo" },
	{ code: "TO", name: "Tonga" },
	{ code: "TT", name: "Trinidad and Tobago" },
	{ code: "TN", name: "Tunisia" },
	{ code: "TR", name: "Turkey", zipLength: 5 },
	{ code: "TM", name: "Turkmenistan" },
	{ code: "TV", name: "Tuvalu" },
	{ code: "UG", name: "Uganda" },
	{ code: "UA", name: "Ukraine" },
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "GB", name: "United Kingdom", zipLength: 7 },
	{ code: "US", name: "United States", zipLength: 5 },
	{ code: "UY", name: "Uruguay" },
	{ code: "UZ", name: "Uzbekistan" },
	{ code: "VU", name: "Vanuatu" },
	{ code: "VE", name: "Venezuela" },
	{ code: "VN", name: "Vietnam" },
	{ code: "YE", name: "Yemen" },
	{ code: "ZM", name: "Zambia" },
	{ code: "ZW", name: "Zimbabwe" },
];

/** Map from country name (lowercase) to Country object for efficient lookups */
export const COUNTRY_BY_NAME = new Map<string, Country>(
	COUNTRIES.map((c) => [c.name.toLowerCase(), c]),
);

export const COUNTRY_BY_CODE = new Map<string, Country>(
	COUNTRIES.map((c) => [c.code, c]),
);

/** PH city list for city autocomplete */
export const PH_CITIES: string[] = [
	"Alaminos",
	"Angeles",
	"Antipolo",
	"Bacolod",
	"Bago",
	"Baguio",
	"Bais",
	"Balanga",
	"Batac",
	"Batangas",
	"Bayawan",
	"Baybay",
	"Bayugan",
	"Biñan",
	"Bislig",
	"Bogo",
	"Borongan",
	"Butuan",
	"Cabadbaran",
	"Cabanatuan",
	"Cadiz",
	"Cagayan de Oro",
	"Calamba",
	"Calapan",
	"Calbayog",
	"Caloocan",
	"Candon",
	"Canlaon",
	"Cauayan",
	"Cavite",
	"Cebu City",
	"Cotabato",
	"Dagupan",
	"Danao",
	"Dapitan",
	"Dasmarinas",
	"Davao City",
	"Digos",
	"Dipolog",
	"Dumaguete",
	"El Salvador",
	"Escalante",
	"Gapan",
	"General Santos",
	"General Trias",
	"Gingoog",
	"Himamaylan",
	"Ilagan",
	"Iligan",
	"Iloilo City",
	"Imus",
	"Iriga",
	"Isabela",
	"Kabankalan",
	"Kidapawan",
	"Koronadal",
	"La Carlota",
	"Lamitan",
	"Laoag",
	"Lapu-Lapu",
	"Las Piñas",
	"Legazpi",
	"Ligao",
	"Lipa",
	"Lucena",
	"Maasin",
	"Mabalacat",
	"Makati",
	"Malabon",
	"Malaybalay",
	"Malolos",
	"Mandaluyong",
	"Mandaue",
	"Manila",
	"Marawi",
	"Marikina",
	"Masbate",
	"Mati",
	"Meycauayan",
	"Muñoz",
	"Muntinlupa",
	"Naga",
	"Navotas",
	"Olongapo",
	"Ormoc",
	"Oroquieta",
	"Ozamiz",
	"Pagadian",
	"Palayan",
	"Panabo",
	"Parañaque",
	"Pasay",
	"Pasig",
	"Passi",
	"Puerto Princesa",
	"Quezon City",
	"Roxas",
	"Sagay",
	"Samal",
	"San Carlos",
	"San Fernando (Pampanga)",
	"San Fernando (La Union)",
	"San Jose",
	"San Jose del Monte",
	"San Juan",
	"San Pablo",
	"Santa Rosa",
	"Santiago",
	"Silay",
	"Sipalay",
	"Sorsogon",
	"Surigao",
	"Tabaco",
	"Tabuk",
	"Tacloban",
	"Tacurong",
	"Tagaytay",
	"Tagbilaran",
	"Taguig",
	"Tagum",
	"Talisay",
	"Tanauan",
	"Tandag",
	"Tangub",
	"Tanjay",
	"Tarlac City",
	"Toledo",
	"Trece Martires",
	"Tuguegarao",
	"Urdaneta",
	"Valencia",
	"Valenzuela",
	"Victorias",
	"Vigan",
	"Zamboanga City",
];
