/**
 * Turning positioned glyph runs into lines and columns.
 *
 * Pure functions, no Nest, no pdfjs — everything here is driven by geometry
 * that a fixture can reproduce exactly, which is what makes the LinkedIn parser
 * testable without shipping a real PDF (and therefore a real person's CV).
 */

export interface PdfTextItem {
  x: number;
  y: number;
  /** Advance width of the run, used for column-boundary checks. */
  w: number;
  /** Font size, derived from the transform. This is the structural grammar. */
  size: number;
  text: string;
  page: number;
}

export interface PdfLine {
  x: number;
  y: number;
  right: number;
  size: number;
  text: string;
  page: number;
}

/** Normalizes the characters a PDF text layer tends to mangle. */
export function normalizeText(raw: string): string {
  return raw
    .normalize('NFKC')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\ufffd/g, '')
    .replace(/\u00a0/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Groups items into visual lines.
 *
 * Callers MUST split by column before calling this. Grouping by y first merges
 * the two columns, because a sidebar entry and a summary line sit at the same
 * height -- the first line of a LinkedIn export then reads
 * "www.linkedin.com/in/david-bato- Stack Engineer @ ...". Column first, then
 * lines within the column.
 *
 * Runs closer than `joinGap` are concatenated without a space, which reassembles
 * "August 2025 - Present " + "(1 year 1 month)" and the education year suffix.
 */
export function groupIntoLines(
  items: PdfTextItem[],
  yTolerance = 2,
  joinGap = 1.5,
): PdfLine[] {
  const buckets: { page: number; y: number; parts: PdfTextItem[] }[] = [];

  for (const item of items) {
    if (!item.text.trim()) continue;
    // Bucketing on y ALONE merges lines from different pages that happen to
    // sit at the same height -- which is most of them, since every page starts
    // its body at the same offset. The page must be part of the key.
    let bucket = buckets.find(
      (b) => b.page === item.page && Math.abs(b.y - item.y) <= yTolerance,
    );
    if (!bucket) {
      bucket = { page: item.page, y: item.y, parts: [] };
      buckets.push(bucket);
    }
    bucket.parts.push(item);
  }

  return buckets
    .sort((a, b) => a.page - b.page || b.y - a.y)
    .map((bucket) => {
      const parts = [...bucket.parts].sort((a, b) => a.x - b.x);
      let text = '';
      let previous: PdfTextItem | null = null;
      for (const part of parts) {
        if (previous && part.x - (previous.x + previous.w) < joinGap) {
          text += part.text;
        } else {
          text += (text ? ' ' : '') + part.text;
        }
        previous = part;
      }
      return {
        x: parts[0].x,
        y: bucket.y,
        right: Math.max(...parts.map((p) => p.x + p.w)),
        size: Math.max(...parts.map((p) => p.size)),
        text: normalizeText(text),
        page: parts[0].page,
      };
    })
    .filter((line) => line.text.length > 0);
}

/** Page footers ("Page 3 of 5") interleave into the text and must go. */
export function isPageFooter(text: string): boolean {
  return /^Page\s+\d+\s+of\s+\d+$/i.test(text.trim());
}

/**
 * Rejoins lines that are one wrapped item.
 *
 * The signal is line LEADING, not width. LinkedIn's PDFs are generated by
 * Apache FOP, which lays out a wrapped continuation at 1.2x the font size and
 * separates distinct list items by that plus a 5pt space-before. Measured on a
 * real export at 10.5pt: 12.60 between the two halves of one certification,
 * 17.60 between certifications -- 8 out of 8 correct with no heuristics.
 *
 * A width-based rule would be wrong, and quietly so: "Full Stack Web
 * Development" (135.3pt, NOT wrapped) is wider than "Introduction to
 * Cybersecurity" (133.6pt, wrapped), so no fill-ratio threshold separates them.
 *
 * Never merges across a page boundary, where the y delta is meaningless.
 */
export function mergeWrappedLines(lines: PdfLine[], slack = 1.25): PdfLine[] {
  const merged: PdfLine[] = [];

  for (const line of lines) {
    const previous = merged[merged.length - 1];
    const isContinuation =
      previous !== undefined &&
      previous.page === line.page &&
      Math.abs(previous.x - line.x) < 1.5 &&
      Math.abs(previous.size - line.size) < 0.6 &&
      previous.y - line.y < line.size * slack;

    if (isContinuation) {
      previous.text = normalizeText(`${previous.text} ${line.text}`);
      previous.right = Math.max(previous.right, line.right);
      previous.y = line.y;
      continue;
    }
    merged.push({ ...line });
  }

  return merged;
}
