import { useEffect, useMemo, useRef, useState } from "react";
import {
  Bot,
  Boxes,
  Minimize2,
  Send,
  Sparkles,
  TriangleAlert,
} from "lucide-react";
import { useRoadmapStore } from "@/stores/roadmapStore";
import type { Roadmap, RoadmapEpic, RoadmapFeature } from "@/types/roadmap";
import type { RoadmapArtifactPreview } from "@/types/roadmapArtifact";
import {
  useRoadmapAiAssistantSession,
  type RoadmapAiChatMessage,
} from "./useRoadmapAiAssistantSession";

interface TryAiFloatingAssistantProps {
  roadmapId: string;
  baseRevision?: number;
  roadmapSnapshot?: Roadmap | null;
  epicsSnapshot?: RoadmapEpic[];
  bottomOffsetPx?: number;
  rightOffsetPx?: number;
  onOpenChange?: (isOpen: boolean) => void;
}

const buildAssistantMessage = (
  content: string,
  parseMode: string,
  options?: {
    intentType?: "smalltalk" | "question" | "roadmap_edit" | "unclear";
    responseMode?: "chat" | "edit_plan";
    artifacts?: RoadmapArtifactPreview[];
  },
): RoadmapAiChatMessage => ({
  id: crypto.randomUUID(),
  role: "assistant",
  content,
  timestamp: new Date().toISOString(),
  parseMode,
  intentType: options?.intentType,
  responseMode: options?.responseMode,
  artifacts: options?.artifacts,
});

const deepClone = <T,>(value: T): T => {
  if (typeof structuredClone === "function") return structuredClone(value);
  return JSON.parse(JSON.stringify(value)) as T;
};

const isEditPrompt = (text: string) =>
  /\b(add|create|move|delete|remove|update|mark|shift|link|unlink|rename|retitle|change)\b/i.test(
    text,
  );

const createMockArtifact = (
  roadmap: Roadmap | null,
  epics: RoadmapEpic[],
  roadmapId: string,
): RoadmapArtifactPreview | null => {
  if (!roadmap) return null;

  const now = new Date().toISOString();
  const snapshot = deepClone<Roadmap>({
    ...roadmap,
    epics: deepClone(epics),
    milestones: deepClone(roadmap.milestones || []),
  });

  const newEpicId = crypto.randomUUID();
  const newFeatureId = crypto.randomUUID();
  const newTaskId = crypto.randomUUID();
  const nextEpicPosition = (snapshot.epics || []).length;

  const newFeature: RoadmapFeature = {
    id: newFeatureId,
    roadmap_id: roadmapId,
    epic_id: newEpicId,
    title: "Mock Feature: AI Draft Flow",
    description: "Generated in mock artifact mode from chat request.",
    status: "not_started",
    position: 0,
    is_deliverable: true,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: newTaskId,
        feature_id: newFeatureId,
        title: "Mock Task: Validate artifact interactions",
        status: "todo",
        priority: "medium",
        position: 0,
        created_at: now,
        updated_at: now,
      },
    ],
  };

  const newEpic: RoadmapEpic = {
    id: newEpicId,
    roadmap_id: roadmapId,
    title: "Mock Epic: Assistant Proposed Changes",
    description: "Preview-only epic generated by local mock assistant.",
    priority: "medium",
    status: "backlog",
    position: nextEpicPosition,
    created_at: now,
    updated_at: now,
    features: [newFeature],
  };

  snapshot.epics = [...(snapshot.epics || []), newEpic];
  snapshot.updated_at = now;

  return {
    artifactId: crypto.randomUUID(),
    title: `Artifact ${new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`,
    summary: "Added 1 mock epic, 1 mock feature, and 1 mock task at the bottom.",
    createdAt: now,
    baseRoadmapId: roadmapId,
    candidateSnapshot: snapshot,
    semanticDiffSummary: {
      node_added: 3,
      node_removed: 0,
      node_moved: 0,
      status_changed: 0,
      date_changed: 0,
      dependency_changed: 0,
    },
    validationIssues: [
      {
        code: "MOCK_PREVIEW",
        severity: "warning",
        path: "/",
        message: "This artifact is frontend mock data and has not been server-validated.",
      },
    ],
    status: "draft",
  };
};

export function TryAiFloatingAssistant({
  roadmapId,
  roadmapSnapshot,
  epicsSnapshot,
  bottomOffsetPx = 20,
  rightOffsetPx = 20,
  onOpenChange,
}: TryAiFloatingAssistantProps) {
  const { isOpen, messages, setIsOpen, appendMessage } =
    useRoadmapAiAssistantSession(roadmapId);
  const [input, setInput] = useState("");
  const [isSending, setIsSending] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  const roadmapFromStore = useRoadmapStore((state) => state.roadmap);
  const epicsFromStore = useRoadmapStore((state) => state.epics);
  const roadmap = roadmapSnapshot ?? roadmapFromStore;
  const epics = epicsSnapshot ?? epicsFromStore;
  const openArtifactTab = useRoadmapStore((state) => state.openArtifactTab);

  const messageCountLabel = useMemo(() => {
    const count = messages.length;
    if (!count) return "New";
    if (count > 99) return "99+";
    return `${count}`;
  }, [messages.length]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
  }, [messages.length, isSending]);

  useEffect(() => {
    onOpenChange?.(isOpen);
  }, [isOpen, onOpenChange]);

  const handleSend = async () => {
    const trimmedMessage = input.trim();
    if (!trimmedMessage || isSending) return;

    setInput("");
    setErrorMessage(null);
    appendMessage({
      id: crypto.randomUUID(),
      role: "user",
      content: trimmedMessage,
      timestamp: new Date().toISOString(),
    });

    setIsSending(true);
    try {
      const editMode = isEditPrompt(trimmedMessage);
      if (!editMode) {
        appendMessage(
          buildAssistantMessage(
            "Mock mode is active. I can still help with planning edits and generate artifact previews when you ask for changes.",
            "mock_chat",
            {
              intentType: "question",
              responseMode: "chat",
            },
          ),
        );
        return;
      }

      const artifact = createMockArtifact(roadmap, epics, roadmapId);
      if (!artifact) {
        appendMessage(
          buildAssistantMessage(
            "I could not build a mock artifact because roadmap data is not ready yet.",
            "mock_error",
          ),
        );
        return;
      }

      appendMessage(
        buildAssistantMessage(
          "I prepared a mock artifact preview. Open it to inspect the visual roadmap changes.",
          "mock_edit_plan",
          {
            intentType: "roadmap_edit",
            responseMode: "edit_plan",
            artifacts: [artifact],
          },
        ),
      );
    } catch (error) {
      const readableError =
        error instanceof Error ? error.message : "Failed to generate mock artifact.";
      setErrorMessage(readableError);
      appendMessage(
        buildAssistantMessage(
          "I couldn't generate a mock artifact. Please try again.",
          "mock_error",
        ),
      );
    } finally {
      setIsSending(false);
    }
  };

  const handleOpenArtifact = (artifact: RoadmapArtifactPreview) => {
    openArtifactTab(artifact);
    appendMessage(
      buildAssistantMessage(`Opened ${artifact.title} in Artifact tab.`, "mock_artifact_opened"),
    );
  };

  const handleInputKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      void handleSend();
    }
  };

  return (
    <>
      {isOpen && (
        <section
          className="fixed z-[90] w-[380px] max-w-[calc(100vw-24px)] h-[540px] bg-white border border-gray-200 rounded-2xl shadow-2xl overflow-hidden flex flex-col"
          style={{ bottom: bottomOffsetPx, right: rightOffsetPx }}
          aria-label="AI Assistant Panel"
        >
          <header className="px-4 py-3 border-b border-gray-200 bg-white flex items-start justify-between gap-3">
            <div>
              <p className="text-sm font-semibold text-gray-900 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-[#ff9933]" />
                Try AI Assistant
              </p>
              <p className="text-[11px] text-gray-500 mt-0.5">
                Mock mode. Click artifact cards to open Artifact tabs.
              </p>
            </div>
            <button
              type="button"
              className="h-8 w-8 inline-flex items-center justify-center rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-100"
              title="Minimize AI assistant"
              onClick={() => setIsOpen(false)}
            >
              <Minimize2 className="w-4 h-4" />
            </button>
          </header>

          <div className="flex-1 overflow-y-auto px-3 py-3 space-y-3 bg-gray-50/40">
            {messages.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-center px-4">
                <Bot className="w-8 h-8 text-gray-400 mb-2" />
                <p className="text-sm text-gray-700 font-medium">
                  Ask for changes to generate mock artifact cards
                </p>
                <p className="text-xs text-gray-500 mt-1">
                  Example: "add an epic for onboarding improvements"
                </p>
              </div>
            ) : (
              messages.map((message) => {
                const artifacts = message.artifacts ?? [];
                return (
                  <article
                    key={message.id}
                    className={`rounded-xl px-3 py-2.5 border ${
                      message.role === "user"
                        ? "bg-white border-orange-200 ml-8"
                        : "bg-white border-gray-200 mr-4"
                    }`}
                  >
                    <div className="flex items-center justify-between gap-2 mb-1.5">
                      <span
                        className={`text-[11px] font-semibold ${
                          message.role === "user" ? "text-orange-600" : "text-gray-700"
                        }`}
                      >
                        {message.role === "user" ? "You" : "Assistant"}
                      </span>
                      <span className="text-[10px] text-gray-400">
                        {new Date(message.timestamp).toLocaleTimeString([], {
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </span>
                    </div>
                    <p className="text-xs text-gray-800 whitespace-pre-wrap leading-relaxed">
                      {message.content}
                    </p>

                    {artifacts.length > 0 && (
                      <div className="mt-2.5 space-y-2">
                        {artifacts.map((artifact) => (
                          <div
                            key={artifact.artifactId}
                            className="rounded-lg border border-orange-200 bg-orange-50/60 p-2.5"
                          >
                            <p className="text-[11px] font-semibold text-orange-700">
                              {artifact.title}
                            </p>
                            <p className="text-[10px] text-orange-700/90 mt-0.5">
                              {artifact.summary}
                            </p>
                            <div className="mt-1.5 text-[10px] text-orange-800/90">
                              Mock issues: {artifact.validationIssues.length}
                            </div>
                            <button
                              type="button"
                              onClick={() => handleOpenArtifact(artifact)}
                              className="mt-2 h-7 px-2.5 rounded-md border border-orange-300 bg-white text-[10px] font-semibold text-orange-700 hover:bg-orange-100 inline-flex items-center gap-1.5"
                            >
                              <Boxes className="w-3.5 h-3.5" />
                              Open Artifact Tab
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </article>
                );
              })
            )}

            {isSending && (
              <div className="rounded-xl px-3 py-2.5 border border-gray-200 bg-white mr-4 text-xs text-gray-600">
                Thinking...
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          <footer className="border-t border-gray-200 bg-white px-3 py-3">
            {errorMessage && (
              <div className="mb-2 rounded-lg border border-red-200 bg-red-50 px-2.5 py-2 text-[11px] text-red-700 flex items-start gap-1.5">
                <TriangleAlert className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                <span>{errorMessage}</span>
              </div>
            )}

            <div className="mb-2 flex items-center justify-between gap-2">
              <span className="text-[10px] text-gray-500">
                Frontend-only mock mode (no API calls)
              </span>
            </div>

            <div className="flex items-center gap-2">
              <input
                type="text"
                value={input}
                onChange={(event) => setInput(event.target.value)}
                onKeyDown={handleInputKeyDown}
                placeholder="Chat or request roadmap edits..."
                className="flex-1 h-10 rounded-xl border border-gray-300 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300"
                disabled={isSending}
              />
              <button
                type="button"
                onClick={() => void handleSend()}
                disabled={isSending || !input.trim()}
                className="h-10 w-10 rounded-xl bg-[#ff9933] text-white inline-flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed hover:bg-[#ff880f] transition-colors"
                title="Send message"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>
          </footer>
        </section>
      )}

      {!isOpen && (
        <button
          type="button"
          className="fixed z-[90] inline-flex items-center gap-2 rounded-full bg-[#ff9933] text-white px-4 py-2.5 shadow-lg hover:bg-[#ff880f] transition-colors"
          style={{ bottom: bottomOffsetPx, right: rightOffsetPx }}
          onClick={() => setIsOpen(true)}
          aria-label="Open AI assistant"
        >
          <Sparkles className="w-4 h-4" />
          <span className="text-sm font-semibold">Try AI</span>
          <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-white/20">
            {messageCountLabel}
          </span>
        </button>
      )}
    </>
  );
}
