import type { ContractRow } from './contracts.service';

export function contractFixture(
  overrides: Partial<ContractRow> = {},
): ContractRow {
  return {
    id: 'contract-1',
    project_id: 'project-1',
    project_title_snapshot: 'Project One',
    consultant_user_id: 'consultant-1',
    relationship_kind: 'client_services',
    scope_mode: 'project_specific',
    contract_family_id: null,
    engagement_id: null,
    version: 1,
    contract_number: 'CTR-001',
    status: 'sent',
    provider_kind: 'individual',
    provider_name: 'Consultant One',
    provider_address: null,
    provider_tin: null,
    provider_email: 'consultant@example.com',
    client_name: 'Client One',
    client_contact_name: null,
    client_address: null,
    client_tin: null,
    client_email: 'client@example.com',
    client_user_id: 'client-1',
    currency: 'USD',
    billing_mode: 'retainer',
    fixed_fee: null,
    time_tracking_mode: 'optional',
    time_approval_mode: 'none',
    allow_manual_time: true,
    time_rounding_minutes: 0,
    weekly_time_limit_minutes: null,
    client_hours_detail_level: 'none',
    billing_timing: 'arrears',
    recurring_fee: 1000,
    client_hourly_rate: null,
    included_hours: null,
    invoice_cadence: 'monthly',
    period_source: 'contract',
    invoice_offset_days: 0,
    due_days: 15,
    invoice_number_prefix: null,
    service_description: 'Delivery',
    payment_method: null,
    service_start_date: '2026-08-01',
    term_count: 1,
    term_unit: 'month',
    service_end_date: '2026-08-31',
    contract_end_date: '2026-08-31',
    auto_renew: false,
    notice_days: null,
    supersedes_contract_id: null,
    amendment_effective_date: null,
    clauses: [],
    services: [],
    notes: null,
    signed_by_consultant_at: null,
    signed_by_consultant_name: null,
    signed_by_consultant_signature_url: null,
    signed_by_consultant_signature_scale: 1,
    signed_by_consultant_signature_offset_x: 0,
    signed_by_consultant_signature_offset_y: 0,
    signed_by_client_at: null,
    signed_by_client_name: null,
    signed_by_client_signature_url: null,
    signed_by_client_signature_scale: 1,
    signed_by_client_signature_offset_x: 0,
    signed_by_client_signature_offset_y: 0,
    created_by: 'consultant-1',
    created_at: '2026-08-01T00:00:00.000Z',
    updated_at: '2026-08-01T00:00:00.000Z',
    ...overrides,
  };
}
