/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkItemsRouteImport } from './routes/work-items'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ProjectPostingRouteImport } from './routes/project-posting'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RoadmapTemplatesRouteRouteImport } from './routes/roadmap-templates/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as RoadmapTemplatesIndexRouteImport } from './routes/roadmap-templates/index'
import { Route as ConsultantIndexRouteImport } from './routes/consultant/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as RoadmapSharedWithMeRouteImport } from './routes/roadmap/shared-with-me'
import { Route as RoadmapTemplatesSlugRouteImport } from './routes/roadmap-templates/$slug'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ProfileProfileIdRouteImport } from './routes/profile/$profileId'
import { Route as FreelancerInvitesRouteImport } from './routes/freelancer/invites'
import { Route as FreelancerGoLiveRouteImport } from './routes/freelancer/go-live'
import { Route as ConsultantTemplatesRouteImport } from './routes/consultant/templates'
import { Route as ConsultantMarketplaceRouteImport } from './routes/consultant/marketplace'
import { Route as ConsultantBrowseRouteImport } from './routes/consultant/browse'
import { Route as ConsultantApplyRouteImport } from './routes/consultant/apply'
import { Route as ConsultantProfileIdRouteImport } from './routes/consultant/$profileId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMatchRouteImport } from './routes/admin/match'
import { Route as AdminApproveAdminRouteImport } from './routes/admin/approve-admin'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as ProjectRoadmapIndexRouteImport } from './routes/project/roadmap/index'
import { Route as TeamsMeInvitesRouteImport } from './routes/teams/me/invites'
import { Route as RoadmapSharedTokenRouteImport } from './routes/roadmap/shared/$token'
import { Route as ProjectProjectIdWorkItemsRouteImport } from './routes/project/$projectId/work-items'
import { Route as ProjectProjectIdTeamRouteImport } from './routes/project/$projectId/team'
import { Route as ProjectProjectIdRoadmapRouteImport } from './routes/project/$projectId/roadmap'
import { Route as ProjectProjectIdResourcesRouteImport } from './routes/project/$projectId/resources'
import { Route as ProjectProjectIdPaymentsRouteImport } from './routes/project/$projectId/payments'
import { Route as ProjectProjectIdOverviewRouteImport } from './routes/project/$projectId/overview'
import { Route as ProjectProjectIdLogsRouteImport } from './routes/project/$projectId/logs'
import { Route as AuthAdminSigninRouteImport } from './routes/auth/admin/signin'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'
import { Route as TeamsTeamIdTimeRouteRouteImport } from './routes/teams/$teamId/time/route'
import { Route as TeamsTeamIdTimeIndexRouteImport } from './routes/teams/$teamId/time/index'
import { Route as TeamsTeamIdSettingsIndexRouteImport } from './routes/teams/$teamId/settings/index'
import { Route as ProjectProjectIdSettingsIndexRouteImport } from './routes/project/$projectId/settings/index'
import { Route as TeamsTeamIdTimeTeamLogsRouteImport } from './routes/teams/$teamId/time/team-logs'
import { Route as TeamsTeamIdTimePayoutsRouteImport } from './routes/teams/$teamId/time/payouts'
import { Route as TeamsTeamIdTimeMyLogsRouteImport } from './routes/teams/$teamId/time/my-logs'
import { Route as TeamsTeamIdSettingsTimeRouteImport } from './routes/teams/$teamId/settings/time'
import { Route as TeamsTeamIdSettingsProjectsRouteImport } from './routes/teams/$teamId/settings/projects'
import { Route as TeamsTeamIdSettingsLogsRouteImport } from './routes/teams/$teamId/settings/logs'
import { Route as TeamsTeamIdSettingsGeneralRouteImport } from './routes/teams/$teamId/settings/general'
import { Route as ProjectRoadmapConvertRoadmapIdRouteImport } from './routes/project/roadmap/convert/$roadmapId'
import { Route as ProjectProjectIdWorkItemsRoadmapIdRouteImport } from './routes/project/$projectId/work-items/$roadmapId'
import { Route as ProjectProjectIdSettingsTimeRouteImport } from './routes/project/$projectId/settings/time'
import { Route as ProjectProjectIdSettingsTeamsRouteImport } from './routes/project/$projectId/settings/teams'
import { Route as ProjectProjectIdSettingsTeamRouteImport } from './routes/project/$projectId/settings/team'
import { Route as ProjectProjectIdSettingsPermissionsRouteImport } from './routes/project/$projectId/settings/permissions'
import { Route as ProjectProjectIdSettingsGeneralRouteImport } from './routes/project/$projectId/settings/general'
import { Route as ProjectProjectIdRoadmapCreateRouteImport } from './routes/project/$projectId/roadmap/create'
import { Route as ProjectProjectIdRoadmapRoadmapIdRouteImport } from './routes/project/$projectId/roadmap/$roadmapId'
import { Route as ProjectProjectIdChatChatRefRouteImport } from './routes/project/$projectId/chat/$chatRef'
import { Route as TeamsTeamIdTimeManageRatesIndexRouteImport } from './routes/teams/$teamId/time/manage-rates/index'
import { Route as TeamsTeamIdTimeManageRatesUserIdRouteImport } from './routes/teams/$teamId/time/manage-rates/$userId'
import { Route as TeamsTeamIdTimeLogLogIdRouteImport } from './routes/teams/$teamId/time/log/$logId'

const WorkItemsRoute = WorkItemsRouteImport.update({
  id: '/work-items',
  path: '/work-items',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPostingRoute = ProjectPostingRouteImport.update({
  id: '/project-posting',
  path: '/project-posting',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapTemplatesRouteRoute = RoadmapTemplatesRouteRouteImport.update({
  id: '/roadmap-templates',
  path: '/roadmap-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapTemplatesIndexRoute = RoadmapTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoadmapTemplatesRouteRoute,
} as any)
const ConsultantIndexRoute = ConsultantIndexRouteImport.update({
  id: '/consultant/',
  path: '/consultant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapSharedWithMeRoute = RoadmapSharedWithMeRouteImport.update({
  id: '/roadmap/shared-with-me',
  path: '/roadmap/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapTemplatesSlugRoute = RoadmapTemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoadmapTemplatesRouteRoute,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerInvitesRoute = FreelancerInvitesRouteImport.update({
  id: '/freelancer/invites',
  path: '/freelancer/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerGoLiveRoute = FreelancerGoLiveRouteImport.update({
  id: '/freelancer/go-live',
  path: '/freelancer/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantTemplatesRoute = ConsultantTemplatesRouteImport.update({
  id: '/consultant/templates',
  path: '/consultant/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantMarketplaceRoute = ConsultantMarketplaceRouteImport.update({
  id: '/consultant/marketplace',
  path: '/consultant/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantBrowseRoute = ConsultantBrowseRouteImport.update({
  id: '/consultant/browse',
  path: '/consultant/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantApplyRoute = ConsultantApplyRouteImport.update({
  id: '/consultant/apply',
  path: '/consultant/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantProfileIdRoute = ConsultantProfileIdRouteImport.update({
  id: '/consultant/$profileId',
  path: '/consultant/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchRoute = AdminMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApproveAdminRoute = AdminApproveAdminRouteImport.update({
  id: '/approve-admin',
  path: '/approve-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const ProjectRoadmapIndexRoute = ProjectRoadmapIndexRouteImport.update({
  id: '/project/roadmap/',
  path: '/project/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsMeInvitesRoute = TeamsMeInvitesRouteImport.update({
  id: '/teams/me/invites',
  path: '/teams/me/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapSharedTokenRoute = RoadmapSharedTokenRouteImport.update({
  id: '/roadmap/shared/$token',
  path: '/roadmap/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdWorkItemsRoute =
  ProjectProjectIdWorkItemsRouteImport.update({
    id: '/work-items',
    path: '/work-items',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTeamRoute = ProjectProjectIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdRoadmapRoute = ProjectProjectIdRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdResourcesRoute =
  ProjectProjectIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdPaymentsRoute =
  ProjectProjectIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdOverviewRoute =
  ProjectProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdLogsRoute = ProjectProjectIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const AuthAdminSigninRoute = AuthAdminSigninRouteImport.update({
  id: '/auth/admin/signin',
  path: '/auth/admin/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdTimeRouteRoute = TeamsTeamIdTimeRouteRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdTimeIndexRoute = TeamsTeamIdTimeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdTimeRouteRoute,
} as any)
const TeamsTeamIdSettingsIndexRoute =
  TeamsTeamIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const ProjectProjectIdSettingsIndexRoute =
  ProjectProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const TeamsTeamIdTimeTeamLogsRoute = TeamsTeamIdTimeTeamLogsRouteImport.update({
  id: '/team-logs',
  path: '/team-logs',
  getParentRoute: () => TeamsTeamIdTimeRouteRoute,
} as any)
const TeamsTeamIdTimePayoutsRoute = TeamsTeamIdTimePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => TeamsTeamIdTimeRouteRoute,
} as any)
const TeamsTeamIdTimeMyLogsRoute = TeamsTeamIdTimeMyLogsRouteImport.update({
  id: '/my-logs',
  path: '/my-logs',
  getParentRoute: () => TeamsTeamIdTimeRouteRoute,
} as any)
const TeamsTeamIdSettingsTimeRoute = TeamsTeamIdSettingsTimeRouteImport.update({
  id: '/settings/time',
  path: '/settings/time',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdSettingsProjectsRoute =
  TeamsTeamIdSettingsProjectsRouteImport.update({
    id: '/settings/projects',
    path: '/settings/projects',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const TeamsTeamIdSettingsLogsRoute = TeamsTeamIdSettingsLogsRouteImport.update({
  id: '/settings/logs',
  path: '/settings/logs',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdSettingsGeneralRoute =
  TeamsTeamIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const ProjectRoadmapConvertRoadmapIdRoute =
  ProjectRoadmapConvertRoadmapIdRouteImport.update({
    id: '/project/roadmap/convert/$roadmapId',
    path: '/project/roadmap/convert/$roadmapId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdWorkItemsRoadmapIdRoute =
  ProjectProjectIdWorkItemsRoadmapIdRouteImport.update({
    id: '/$roadmapId',
    path: '/$roadmapId',
    getParentRoute: () => ProjectProjectIdWorkItemsRoute,
  } as any)
const ProjectProjectIdSettingsTimeRoute =
  ProjectProjectIdSettingsTimeRouteImport.update({
    id: '/settings/time',
    path: '/settings/time',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsTeamsRoute =
  ProjectProjectIdSettingsTeamsRouteImport.update({
    id: '/settings/teams',
    path: '/settings/teams',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsTeamRoute =
  ProjectProjectIdSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsPermissionsRoute =
  ProjectProjectIdSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsGeneralRoute =
  ProjectProjectIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdRoadmapCreateRoute =
  ProjectProjectIdRoadmapCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ProjectProjectIdRoadmapRoute,
  } as any)
const ProjectProjectIdRoadmapRoadmapIdRoute =
  ProjectProjectIdRoadmapRoadmapIdRouteImport.update({
    id: '/$roadmapId',
    path: '/$roadmapId',
    getParentRoute: () => ProjectProjectIdRoadmapRoute,
  } as any)
const ProjectProjectIdChatChatRefRoute =
  ProjectProjectIdChatChatRefRouteImport.update({
    id: '/chat/$chatRef',
    path: '/chat/$chatRef',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const TeamsTeamIdTimeManageRatesIndexRoute =
  TeamsTeamIdTimeManageRatesIndexRouteImport.update({
    id: '/manage-rates/',
    path: '/manage-rates/',
    getParentRoute: () => TeamsTeamIdTimeRouteRoute,
  } as any)
const TeamsTeamIdTimeManageRatesUserIdRoute =
  TeamsTeamIdTimeManageRatesUserIdRouteImport.update({
    id: '/manage-rates/$userId',
    path: '/manage-rates/$userId',
    getParentRoute: () => TeamsTeamIdTimeRouteRoute,
  } as any)
const TeamsTeamIdTimeLogLogIdRoute = TeamsTeamIdTimeLogLogIdRouteImport.update({
  id: '/log/$logId',
  path: '/log/$logId',
  getParentRoute: () => TeamsTeamIdTimeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roadmap-templates': typeof RoadmapTemplatesRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/meetings': typeof MeetingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/project-posting': typeof ProjectPostingRoute
  '/welcome': typeof WelcomeRoute
  '/work-items': typeof WorkItemsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/consultant/marketplace': typeof ConsultantMarketplaceRoute
  '/consultant/templates': typeof ConsultantTemplatesRoute
  '/freelancer/go-live': typeof FreelancerGoLiveRoute
  '/freelancer/invites': typeof FreelancerInvitesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap-templates/$slug': typeof RoadmapTemplatesSlugRoute
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/roadmap-templates/': typeof RoadmapTemplatesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamId/time': typeof TeamsTeamIdTimeRouteRouteWithChildren
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/logs': typeof ProjectProjectIdLogsRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/resources': typeof ProjectProjectIdResourcesRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/team': typeof ProjectProjectIdTeamRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRouteWithChildren
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/teams/me/invites': typeof TeamsMeInvitesRoute
  '/project/roadmap': typeof ProjectRoadmapIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/project/$projectId/chat/$chatRef': typeof ProjectProjectIdChatChatRefRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
  '/project/$projectId/roadmap/create': typeof ProjectProjectIdRoadmapCreateRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/permissions': typeof ProjectProjectIdSettingsPermissionsRoute
  '/project/$projectId/settings/team': typeof ProjectProjectIdSettingsTeamRoute
  '/project/$projectId/settings/teams': typeof ProjectProjectIdSettingsTeamsRoute
  '/project/$projectId/settings/time': typeof ProjectProjectIdSettingsTimeRoute
  '/project/$projectId/work-items/$roadmapId': typeof ProjectProjectIdWorkItemsRoadmapIdRoute
  '/project/roadmap/convert/$roadmapId': typeof ProjectRoadmapConvertRoadmapIdRoute
  '/teams/$teamId/settings/general': typeof TeamsTeamIdSettingsGeneralRoute
  '/teams/$teamId/settings/logs': typeof TeamsTeamIdSettingsLogsRoute
  '/teams/$teamId/settings/projects': typeof TeamsTeamIdSettingsProjectsRoute
  '/teams/$teamId/settings/time': typeof TeamsTeamIdSettingsTimeRoute
  '/teams/$teamId/time/my-logs': typeof TeamsTeamIdTimeMyLogsRoute
  '/teams/$teamId/time/payouts': typeof TeamsTeamIdTimePayoutsRoute
  '/teams/$teamId/time/team-logs': typeof TeamsTeamIdTimeTeamLogsRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsIndexRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsIndexRoute
  '/teams/$teamId/time/': typeof TeamsTeamIdTimeIndexRoute
  '/teams/$teamId/time/log/$logId': typeof TeamsTeamIdTimeLogLogIdRoute
  '/teams/$teamId/time/manage-rates/$userId': typeof TeamsTeamIdTimeManageRatesUserIdRoute
  '/teams/$teamId/time/manage-rates': typeof TeamsTeamIdTimeManageRatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/meetings': typeof MeetingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/project-posting': typeof ProjectPostingRoute
  '/welcome': typeof WelcomeRoute
  '/work-items': typeof WorkItemsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/consultant/marketplace': typeof ConsultantMarketplaceRoute
  '/consultant/templates': typeof ConsultantTemplatesRoute
  '/freelancer/go-live': typeof FreelancerGoLiveRoute
  '/freelancer/invites': typeof FreelancerInvitesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap-templates/$slug': typeof RoadmapTemplatesSlugRoute
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/admin': typeof AdminIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/roadmap-templates': typeof RoadmapTemplatesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/logs': typeof ProjectProjectIdLogsRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/resources': typeof ProjectProjectIdResourcesRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/team': typeof ProjectProjectIdTeamRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRouteWithChildren
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/teams/me/invites': typeof TeamsMeInvitesRoute
  '/project/roadmap': typeof ProjectRoadmapIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/project/$projectId/chat/$chatRef': typeof ProjectProjectIdChatChatRefRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
  '/project/$projectId/roadmap/create': typeof ProjectProjectIdRoadmapCreateRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/permissions': typeof ProjectProjectIdSettingsPermissionsRoute
  '/project/$projectId/settings/team': typeof ProjectProjectIdSettingsTeamRoute
  '/project/$projectId/settings/teams': typeof ProjectProjectIdSettingsTeamsRoute
  '/project/$projectId/settings/time': typeof ProjectProjectIdSettingsTimeRoute
  '/project/$projectId/work-items/$roadmapId': typeof ProjectProjectIdWorkItemsRoadmapIdRoute
  '/project/roadmap/convert/$roadmapId': typeof ProjectRoadmapConvertRoadmapIdRoute
  '/teams/$teamId/settings/general': typeof TeamsTeamIdSettingsGeneralRoute
  '/teams/$teamId/settings/logs': typeof TeamsTeamIdSettingsLogsRoute
  '/teams/$teamId/settings/projects': typeof TeamsTeamIdSettingsProjectsRoute
  '/teams/$teamId/settings/time': typeof TeamsTeamIdSettingsTimeRoute
  '/teams/$teamId/time/my-logs': typeof TeamsTeamIdTimeMyLogsRoute
  '/teams/$teamId/time/payouts': typeof TeamsTeamIdTimePayoutsRoute
  '/teams/$teamId/time/team-logs': typeof TeamsTeamIdTimeTeamLogsRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsIndexRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsIndexRoute
  '/teams/$teamId/time': typeof TeamsTeamIdTimeIndexRoute
  '/teams/$teamId/time/log/$logId': typeof TeamsTeamIdTimeLogLogIdRoute
  '/teams/$teamId/time/manage-rates/$userId': typeof TeamsTeamIdTimeManageRatesUserIdRoute
  '/teams/$teamId/time/manage-rates': typeof TeamsTeamIdTimeManageRatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roadmap-templates': typeof RoadmapTemplatesRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/meetings': typeof MeetingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/project-posting': typeof ProjectPostingRoute
  '/welcome': typeof WelcomeRoute
  '/work-items': typeof WorkItemsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/consultant/marketplace': typeof ConsultantMarketplaceRoute
  '/consultant/templates': typeof ConsultantTemplatesRoute
  '/freelancer/go-live': typeof FreelancerGoLiveRoute
  '/freelancer/invites': typeof FreelancerInvitesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap-templates/$slug': typeof RoadmapTemplatesSlugRoute
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/roadmap-templates/': typeof RoadmapTemplatesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamId/time': typeof TeamsTeamIdTimeRouteRouteWithChildren
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/logs': typeof ProjectProjectIdLogsRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/resources': typeof ProjectProjectIdResourcesRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/team': typeof ProjectProjectIdTeamRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRouteWithChildren
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/teams/me/invites': typeof TeamsMeInvitesRoute
  '/project/roadmap/': typeof ProjectRoadmapIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/project/$projectId/chat/$chatRef': typeof ProjectProjectIdChatChatRefRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
  '/project/$projectId/roadmap/create': typeof ProjectProjectIdRoadmapCreateRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/permissions': typeof ProjectProjectIdSettingsPermissionsRoute
  '/project/$projectId/settings/team': typeof ProjectProjectIdSettingsTeamRoute
  '/project/$projectId/settings/teams': typeof ProjectProjectIdSettingsTeamsRoute
  '/project/$projectId/settings/time': typeof ProjectProjectIdSettingsTimeRoute
  '/project/$projectId/work-items/$roadmapId': typeof ProjectProjectIdWorkItemsRoadmapIdRoute
  '/project/roadmap/convert/$roadmapId': typeof ProjectRoadmapConvertRoadmapIdRoute
  '/teams/$teamId/settings/general': typeof TeamsTeamIdSettingsGeneralRoute
  '/teams/$teamId/settings/logs': typeof TeamsTeamIdSettingsLogsRoute
  '/teams/$teamId/settings/projects': typeof TeamsTeamIdSettingsProjectsRoute
  '/teams/$teamId/settings/time': typeof TeamsTeamIdSettingsTimeRoute
  '/teams/$teamId/time/my-logs': typeof TeamsTeamIdTimeMyLogsRoute
  '/teams/$teamId/time/payouts': typeof TeamsTeamIdTimePayoutsRoute
  '/teams/$teamId/time/team-logs': typeof TeamsTeamIdTimeTeamLogsRoute
  '/project/$projectId/settings/': typeof ProjectProjectIdSettingsIndexRoute
  '/teams/$teamId/settings/': typeof TeamsTeamIdSettingsIndexRoute
  '/teams/$teamId/time/': typeof TeamsTeamIdTimeIndexRoute
  '/teams/$teamId/time/log/$logId': typeof TeamsTeamIdTimeLogLogIdRoute
  '/teams/$teamId/time/manage-rates/$userId': typeof TeamsTeamIdTimeManageRatesUserIdRoute
  '/teams/$teamId/time/manage-rates/': typeof TeamsTeamIdTimeManageRatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/roadmap-templates'
    | '/admin'
    | '/command-center'
    | '/dashboard'
    | '/inbox'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/project-posting'
    | '/welcome'
    | '/work-items'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/consultant/marketplace'
    | '/consultant/templates'
    | '/freelancer/go-live'
    | '/freelancer/invites'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap-templates/$slug'
    | '/roadmap/shared-with-me'
    | '/settings/appearance'
    | '/teams/$teamId'
    | '/admin/'
    | '/consultant'
    | '/roadmap-templates/'
    | '/teams'
    | '/teams/$teamId/time'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/logs'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/resources'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/team'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/teams/me/invites'
    | '/project/roadmap'
    | '/teams/$teamId/'
    | '/project/$projectId/chat/$chatRef'
    | '/project/$projectId/roadmap/$roadmapId'
    | '/project/$projectId/roadmap/create'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/permissions'
    | '/project/$projectId/settings/team'
    | '/project/$projectId/settings/teams'
    | '/project/$projectId/settings/time'
    | '/project/$projectId/work-items/$roadmapId'
    | '/project/roadmap/convert/$roadmapId'
    | '/teams/$teamId/settings/general'
    | '/teams/$teamId/settings/logs'
    | '/teams/$teamId/settings/projects'
    | '/teams/$teamId/settings/time'
    | '/teams/$teamId/time/my-logs'
    | '/teams/$teamId/time/payouts'
    | '/teams/$teamId/time/team-logs'
    | '/project/$projectId/settings'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/time/'
    | '/teams/$teamId/time/log/$logId'
    | '/teams/$teamId/time/manage-rates/$userId'
    | '/teams/$teamId/time/manage-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center'
    | '/dashboard'
    | '/inbox'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/project-posting'
    | '/welcome'
    | '/work-items'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/consultant/marketplace'
    | '/consultant/templates'
    | '/freelancer/go-live'
    | '/freelancer/invites'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap-templates/$slug'
    | '/roadmap/shared-with-me'
    | '/settings/appearance'
    | '/admin'
    | '/consultant'
    | '/roadmap-templates'
    | '/teams'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/logs'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/resources'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/team'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/teams/me/invites'
    | '/project/roadmap'
    | '/teams/$teamId'
    | '/project/$projectId/chat/$chatRef'
    | '/project/$projectId/roadmap/$roadmapId'
    | '/project/$projectId/roadmap/create'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/permissions'
    | '/project/$projectId/settings/team'
    | '/project/$projectId/settings/teams'
    | '/project/$projectId/settings/time'
    | '/project/$projectId/work-items/$roadmapId'
    | '/project/roadmap/convert/$roadmapId'
    | '/teams/$teamId/settings/general'
    | '/teams/$teamId/settings/logs'
    | '/teams/$teamId/settings/projects'
    | '/teams/$teamId/settings/time'
    | '/teams/$teamId/time/my-logs'
    | '/teams/$teamId/time/payouts'
    | '/teams/$teamId/time/team-logs'
    | '/project/$projectId/settings'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/time'
    | '/teams/$teamId/time/log/$logId'
    | '/teams/$teamId/time/manage-rates/$userId'
    | '/teams/$teamId/time/manage-rates'
  id:
    | '__root__'
    | '/'
    | '/roadmap-templates'
    | '/admin'
    | '/command-center'
    | '/dashboard'
    | '/inbox'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/project-posting'
    | '/welcome'
    | '/work-items'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/consultant/marketplace'
    | '/consultant/templates'
    | '/freelancer/go-live'
    | '/freelancer/invites'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap-templates/$slug'
    | '/roadmap/shared-with-me'
    | '/settings/appearance'
    | '/teams/$teamId'
    | '/admin/'
    | '/consultant/'
    | '/roadmap-templates/'
    | '/teams/'
    | '/teams/$teamId/time'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/logs'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/resources'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/team'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/teams/me/invites'
    | '/project/roadmap/'
    | '/teams/$teamId/'
    | '/project/$projectId/chat/$chatRef'
    | '/project/$projectId/roadmap/$roadmapId'
    | '/project/$projectId/roadmap/create'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/permissions'
    | '/project/$projectId/settings/team'
    | '/project/$projectId/settings/teams'
    | '/project/$projectId/settings/time'
    | '/project/$projectId/work-items/$roadmapId'
    | '/project/roadmap/convert/$roadmapId'
    | '/teams/$teamId/settings/general'
    | '/teams/$teamId/settings/logs'
    | '/teams/$teamId/settings/projects'
    | '/teams/$teamId/settings/time'
    | '/teams/$teamId/time/my-logs'
    | '/teams/$teamId/time/payouts'
    | '/teams/$teamId/time/team-logs'
    | '/project/$projectId/settings/'
    | '/teams/$teamId/settings/'
    | '/teams/$teamId/time/'
    | '/teams/$teamId/time/log/$logId'
    | '/teams/$teamId/time/manage-rates/$userId'
    | '/teams/$teamId/time/manage-rates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoadmapTemplatesRouteRoute: typeof RoadmapTemplatesRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CommandCenterRoute: typeof CommandCenterRoute
  DashboardRoute: typeof DashboardRoute
  InboxRoute: typeof InboxRoute
  MeetingsRoute: typeof MeetingsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectPostingRoute: typeof ProjectPostingRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkItemsRoute: typeof WorkItemsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ConsultantProfileIdRoute: typeof ConsultantProfileIdRoute
  ConsultantApplyRoute: typeof ConsultantApplyRoute
  ConsultantBrowseRoute: typeof ConsultantBrowseRoute
  ConsultantMarketplaceRoute: typeof ConsultantMarketplaceRoute
  ConsultantTemplatesRoute: typeof ConsultantTemplatesRoute
  FreelancerGoLiveRoute: typeof FreelancerGoLiveRoute
  FreelancerInvitesRoute: typeof FreelancerInvitesRoute
  ProfileProfileIdRoute: typeof ProfileProfileIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  RoadmapSharedWithMeRoute: typeof RoadmapSharedWithMeRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRouteWithChildren
  ConsultantIndexRoute: typeof ConsultantIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthAdminSigninRoute: typeof AuthAdminSigninRoute
  RoadmapSharedTokenRoute: typeof RoadmapSharedTokenRoute
  TeamsMeInvitesRoute: typeof TeamsMeInvitesRoute
  ProjectRoadmapIndexRoute: typeof ProjectRoadmapIndexRoute
  ProjectRoadmapConvertRoadmapIdRoute: typeof ProjectRoadmapConvertRoadmapIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-items': {
      id: '/work-items'
      path: '/work-items'
      fullPath: '/work-items'
      preLoaderRoute: typeof WorkItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-posting': {
      id: '/project-posting'
      path: '/project-posting'
      fullPath: '/project-posting'
      preLoaderRoute: typeof ProjectPostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap-templates': {
      id: '/roadmap-templates'
      path: '/roadmap-templates'
      fullPath: '/roadmap-templates'
      preLoaderRoute: typeof RoadmapTemplatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap-templates/': {
      id: '/roadmap-templates/'
      path: '/'
      fullPath: '/roadmap-templates/'
      preLoaderRoute: typeof RoadmapTemplatesIndexRouteImport
      parentRoute: typeof RoadmapTemplatesRouteRoute
    }
    '/consultant/': {
      id: '/consultant/'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/shared-with-me': {
      id: '/roadmap/shared-with-me'
      path: '/roadmap/shared-with-me'
      fullPath: '/roadmap/shared-with-me'
      preLoaderRoute: typeof RoadmapSharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap-templates/$slug': {
      id: '/roadmap-templates/$slug'
      path: '/$slug'
      fullPath: '/roadmap-templates/$slug'
      preLoaderRoute: typeof RoadmapTemplatesSlugRouteImport
      parentRoute: typeof RoadmapTemplatesRouteRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/invites': {
      id: '/freelancer/invites'
      path: '/freelancer/invites'
      fullPath: '/freelancer/invites'
      preLoaderRoute: typeof FreelancerInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/go-live': {
      id: '/freelancer/go-live'
      path: '/freelancer/go-live'
      fullPath: '/freelancer/go-live'
      preLoaderRoute: typeof FreelancerGoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/templates': {
      id: '/consultant/templates'
      path: '/consultant/templates'
      fullPath: '/consultant/templates'
      preLoaderRoute: typeof ConsultantTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/marketplace': {
      id: '/consultant/marketplace'
      path: '/consultant/marketplace'
      fullPath: '/consultant/marketplace'
      preLoaderRoute: typeof ConsultantMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/browse': {
      id: '/consultant/browse'
      path: '/consultant/browse'
      fullPath: '/consultant/browse'
      preLoaderRoute: typeof ConsultantBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/apply': {
      id: '/consultant/apply'
      path: '/consultant/apply'
      fullPath: '/consultant/apply'
      preLoaderRoute: typeof ConsultantApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/$profileId': {
      id: '/consultant/$profileId'
      path: '/consultant/$profileId'
      fullPath: '/consultant/$profileId'
      preLoaderRoute: typeof ConsultantProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/match': {
      id: '/admin/match'
      path: '/match'
      fullPath: '/admin/match'
      preLoaderRoute: typeof AdminMatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approve-admin': {
      id: '/admin/approve-admin'
      path: '/approve-admin'
      fullPath: '/admin/approve-admin'
      preLoaderRoute: typeof AdminApproveAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/project/roadmap/': {
      id: '/project/roadmap/'
      path: '/project/roadmap'
      fullPath: '/project/roadmap'
      preLoaderRoute: typeof ProjectRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/me/invites': {
      id: '/teams/me/invites'
      path: '/teams/me/invites'
      fullPath: '/teams/me/invites'
      preLoaderRoute: typeof TeamsMeInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/shared/$token': {
      id: '/roadmap/shared/$token'
      path: '/roadmap/shared/$token'
      fullPath: '/roadmap/shared/$token'
      preLoaderRoute: typeof RoadmapSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/work-items': {
      id: '/project/$projectId/work-items'
      path: '/work-items'
      fullPath: '/project/$projectId/work-items'
      preLoaderRoute: typeof ProjectProjectIdWorkItemsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/team': {
      id: '/project/$projectId/team'
      path: '/team'
      fullPath: '/project/$projectId/team'
      preLoaderRoute: typeof ProjectProjectIdTeamRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmap': {
      id: '/project/$projectId/roadmap'
      path: '/roadmap'
      fullPath: '/project/$projectId/roadmap'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/resources': {
      id: '/project/$projectId/resources'
      path: '/resources'
      fullPath: '/project/$projectId/resources'
      preLoaderRoute: typeof ProjectProjectIdResourcesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/payments': {
      id: '/project/$projectId/payments'
      path: '/payments'
      fullPath: '/project/$projectId/payments'
      preLoaderRoute: typeof ProjectProjectIdPaymentsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/overview': {
      id: '/project/$projectId/overview'
      path: '/overview'
      fullPath: '/project/$projectId/overview'
      preLoaderRoute: typeof ProjectProjectIdOverviewRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/logs': {
      id: '/project/$projectId/logs'
      path: '/logs'
      fullPath: '/project/$projectId/logs'
      preLoaderRoute: typeof ProjectProjectIdLogsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/auth/admin/signin': {
      id: '/auth/admin/signin'
      path: '/auth/admin/signin'
      fullPath: '/auth/admin/signin'
      preLoaderRoute: typeof AuthAdminSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/time': {
      id: '/teams/$teamId/time'
      path: '/time'
      fullPath: '/teams/$teamId/time'
      preLoaderRoute: typeof TeamsTeamIdTimeRouteRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/time/': {
      id: '/teams/$teamId/time/'
      path: '/'
      fullPath: '/teams/$teamId/time/'
      preLoaderRoute: typeof TeamsTeamIdTimeIndexRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
    '/teams/$teamId/settings/': {
      id: '/teams/$teamId/settings/'
      path: '/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof TeamsTeamIdSettingsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/project/$projectId/settings/': {
      id: '/project/$projectId/settings/'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/teams/$teamId/time/team-logs': {
      id: '/teams/$teamId/time/team-logs'
      path: '/team-logs'
      fullPath: '/teams/$teamId/time/team-logs'
      preLoaderRoute: typeof TeamsTeamIdTimeTeamLogsRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
    '/teams/$teamId/time/payouts': {
      id: '/teams/$teamId/time/payouts'
      path: '/payouts'
      fullPath: '/teams/$teamId/time/payouts'
      preLoaderRoute: typeof TeamsTeamIdTimePayoutsRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
    '/teams/$teamId/time/my-logs': {
      id: '/teams/$teamId/time/my-logs'
      path: '/my-logs'
      fullPath: '/teams/$teamId/time/my-logs'
      preLoaderRoute: typeof TeamsTeamIdTimeMyLogsRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
    '/teams/$teamId/settings/time': {
      id: '/teams/$teamId/settings/time'
      path: '/settings/time'
      fullPath: '/teams/$teamId/settings/time'
      preLoaderRoute: typeof TeamsTeamIdSettingsTimeRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/settings/projects': {
      id: '/teams/$teamId/settings/projects'
      path: '/settings/projects'
      fullPath: '/teams/$teamId/settings/projects'
      preLoaderRoute: typeof TeamsTeamIdSettingsProjectsRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/settings/logs': {
      id: '/teams/$teamId/settings/logs'
      path: '/settings/logs'
      fullPath: '/teams/$teamId/settings/logs'
      preLoaderRoute: typeof TeamsTeamIdSettingsLogsRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/settings/general': {
      id: '/teams/$teamId/settings/general'
      path: '/settings/general'
      fullPath: '/teams/$teamId/settings/general'
      preLoaderRoute: typeof TeamsTeamIdSettingsGeneralRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/project/roadmap/convert/$roadmapId': {
      id: '/project/roadmap/convert/$roadmapId'
      path: '/project/roadmap/convert/$roadmapId'
      fullPath: '/project/roadmap/convert/$roadmapId'
      preLoaderRoute: typeof ProjectRoadmapConvertRoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/work-items/$roadmapId': {
      id: '/project/$projectId/work-items/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/project/$projectId/work-items/$roadmapId'
      preLoaderRoute: typeof ProjectProjectIdWorkItemsRoadmapIdRouteImport
      parentRoute: typeof ProjectProjectIdWorkItemsRoute
    }
    '/project/$projectId/settings/time': {
      id: '/project/$projectId/settings/time'
      path: '/settings/time'
      fullPath: '/project/$projectId/settings/time'
      preLoaderRoute: typeof ProjectProjectIdSettingsTimeRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/teams': {
      id: '/project/$projectId/settings/teams'
      path: '/settings/teams'
      fullPath: '/project/$projectId/settings/teams'
      preLoaderRoute: typeof ProjectProjectIdSettingsTeamsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/team': {
      id: '/project/$projectId/settings/team'
      path: '/settings/team'
      fullPath: '/project/$projectId/settings/team'
      preLoaderRoute: typeof ProjectProjectIdSettingsTeamRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/permissions': {
      id: '/project/$projectId/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/project/$projectId/settings/permissions'
      preLoaderRoute: typeof ProjectProjectIdSettingsPermissionsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/general': {
      id: '/project/$projectId/settings/general'
      path: '/settings/general'
      fullPath: '/project/$projectId/settings/general'
      preLoaderRoute: typeof ProjectProjectIdSettingsGeneralRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmap/create': {
      id: '/project/$projectId/roadmap/create'
      path: '/create'
      fullPath: '/project/$projectId/roadmap/create'
      preLoaderRoute: typeof ProjectProjectIdRoadmapCreateRouteImport
      parentRoute: typeof ProjectProjectIdRoadmapRoute
    }
    '/project/$projectId/roadmap/$roadmapId': {
      id: '/project/$projectId/roadmap/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/project/$projectId/roadmap/$roadmapId'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRoadmapIdRouteImport
      parentRoute: typeof ProjectProjectIdRoadmapRoute
    }
    '/project/$projectId/chat/$chatRef': {
      id: '/project/$projectId/chat/$chatRef'
      path: '/chat/$chatRef'
      fullPath: '/project/$projectId/chat/$chatRef'
      preLoaderRoute: typeof ProjectProjectIdChatChatRefRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/teams/$teamId/time/manage-rates/': {
      id: '/teams/$teamId/time/manage-rates/'
      path: '/manage-rates'
      fullPath: '/teams/$teamId/time/manage-rates'
      preLoaderRoute: typeof TeamsTeamIdTimeManageRatesIndexRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
    '/teams/$teamId/time/manage-rates/$userId': {
      id: '/teams/$teamId/time/manage-rates/$userId'
      path: '/manage-rates/$userId'
      fullPath: '/teams/$teamId/time/manage-rates/$userId'
      preLoaderRoute: typeof TeamsTeamIdTimeManageRatesUserIdRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
    '/teams/$teamId/time/log/$logId': {
      id: '/teams/$teamId/time/log/$logId'
      path: '/log/$logId'
      fullPath: '/teams/$teamId/time/log/$logId'
      preLoaderRoute: typeof TeamsTeamIdTimeLogLogIdRouteImport
      parentRoute: typeof TeamsTeamIdTimeRouteRoute
    }
  }
}

interface RoadmapTemplatesRouteRouteChildren {
  RoadmapTemplatesSlugRoute: typeof RoadmapTemplatesSlugRoute
  RoadmapTemplatesIndexRoute: typeof RoadmapTemplatesIndexRoute
}

const RoadmapTemplatesRouteRouteChildren: RoadmapTemplatesRouteRouteChildren = {
  RoadmapTemplatesSlugRoute: RoadmapTemplatesSlugRoute,
  RoadmapTemplatesIndexRoute: RoadmapTemplatesIndexRoute,
}

const RoadmapTemplatesRouteRouteWithChildren =
  RoadmapTemplatesRouteRoute._addFileChildren(
    RoadmapTemplatesRouteRouteChildren,
  )

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminApproveAdminRoute: typeof AdminApproveAdminRoute
  AdminMatchRoute: typeof AdminMatchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminApproveAdminRoute: AdminApproveAdminRoute,
  AdminMatchRoute: AdminMatchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectProjectIdRoadmapRouteChildren {
  ProjectProjectIdRoadmapRoadmapIdRoute: typeof ProjectProjectIdRoadmapRoadmapIdRoute
  ProjectProjectIdRoadmapCreateRoute: typeof ProjectProjectIdRoadmapCreateRoute
}

const ProjectProjectIdRoadmapRouteChildren: ProjectProjectIdRoadmapRouteChildren =
  {
    ProjectProjectIdRoadmapRoadmapIdRoute:
      ProjectProjectIdRoadmapRoadmapIdRoute,
    ProjectProjectIdRoadmapCreateRoute: ProjectProjectIdRoadmapCreateRoute,
  }

const ProjectProjectIdRoadmapRouteWithChildren =
  ProjectProjectIdRoadmapRoute._addFileChildren(
    ProjectProjectIdRoadmapRouteChildren,
  )

interface ProjectProjectIdWorkItemsRouteChildren {
  ProjectProjectIdWorkItemsRoadmapIdRoute: typeof ProjectProjectIdWorkItemsRoadmapIdRoute
}

const ProjectProjectIdWorkItemsRouteChildren: ProjectProjectIdWorkItemsRouteChildren =
  {
    ProjectProjectIdWorkItemsRoadmapIdRoute:
      ProjectProjectIdWorkItemsRoadmapIdRoute,
  }

const ProjectProjectIdWorkItemsRouteWithChildren =
  ProjectProjectIdWorkItemsRoute._addFileChildren(
    ProjectProjectIdWorkItemsRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdLogsRoute: typeof ProjectProjectIdLogsRoute
  ProjectProjectIdOverviewRoute: typeof ProjectProjectIdOverviewRoute
  ProjectProjectIdPaymentsRoute: typeof ProjectProjectIdPaymentsRoute
  ProjectProjectIdResourcesRoute: typeof ProjectProjectIdResourcesRoute
  ProjectProjectIdRoadmapRoute: typeof ProjectProjectIdRoadmapRouteWithChildren
  ProjectProjectIdTeamRoute: typeof ProjectProjectIdTeamRoute
  ProjectProjectIdWorkItemsRoute: typeof ProjectProjectIdWorkItemsRouteWithChildren
  ProjectProjectIdChatChatRefRoute: typeof ProjectProjectIdChatChatRefRoute
  ProjectProjectIdSettingsGeneralRoute: typeof ProjectProjectIdSettingsGeneralRoute
  ProjectProjectIdSettingsPermissionsRoute: typeof ProjectProjectIdSettingsPermissionsRoute
  ProjectProjectIdSettingsTeamRoute: typeof ProjectProjectIdSettingsTeamRoute
  ProjectProjectIdSettingsTeamsRoute: typeof ProjectProjectIdSettingsTeamsRoute
  ProjectProjectIdSettingsTimeRoute: typeof ProjectProjectIdSettingsTimeRoute
  ProjectProjectIdSettingsIndexRoute: typeof ProjectProjectIdSettingsIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdLogsRoute: ProjectProjectIdLogsRoute,
  ProjectProjectIdOverviewRoute: ProjectProjectIdOverviewRoute,
  ProjectProjectIdPaymentsRoute: ProjectProjectIdPaymentsRoute,
  ProjectProjectIdResourcesRoute: ProjectProjectIdResourcesRoute,
  ProjectProjectIdRoadmapRoute: ProjectProjectIdRoadmapRouteWithChildren,
  ProjectProjectIdTeamRoute: ProjectProjectIdTeamRoute,
  ProjectProjectIdWorkItemsRoute: ProjectProjectIdWorkItemsRouteWithChildren,
  ProjectProjectIdChatChatRefRoute: ProjectProjectIdChatChatRefRoute,
  ProjectProjectIdSettingsGeneralRoute: ProjectProjectIdSettingsGeneralRoute,
  ProjectProjectIdSettingsPermissionsRoute:
    ProjectProjectIdSettingsPermissionsRoute,
  ProjectProjectIdSettingsTeamRoute: ProjectProjectIdSettingsTeamRoute,
  ProjectProjectIdSettingsTeamsRoute: ProjectProjectIdSettingsTeamsRoute,
  ProjectProjectIdSettingsTimeRoute: ProjectProjectIdSettingsTimeRoute,
  ProjectProjectIdSettingsIndexRoute: ProjectProjectIdSettingsIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

interface TeamsTeamIdTimeRouteRouteChildren {
  TeamsTeamIdTimeMyLogsRoute: typeof TeamsTeamIdTimeMyLogsRoute
  TeamsTeamIdTimePayoutsRoute: typeof TeamsTeamIdTimePayoutsRoute
  TeamsTeamIdTimeTeamLogsRoute: typeof TeamsTeamIdTimeTeamLogsRoute
  TeamsTeamIdTimeIndexRoute: typeof TeamsTeamIdTimeIndexRoute
  TeamsTeamIdTimeLogLogIdRoute: typeof TeamsTeamIdTimeLogLogIdRoute
  TeamsTeamIdTimeManageRatesUserIdRoute: typeof TeamsTeamIdTimeManageRatesUserIdRoute
  TeamsTeamIdTimeManageRatesIndexRoute: typeof TeamsTeamIdTimeManageRatesIndexRoute
}

const TeamsTeamIdTimeRouteRouteChildren: TeamsTeamIdTimeRouteRouteChildren = {
  TeamsTeamIdTimeMyLogsRoute: TeamsTeamIdTimeMyLogsRoute,
  TeamsTeamIdTimePayoutsRoute: TeamsTeamIdTimePayoutsRoute,
  TeamsTeamIdTimeTeamLogsRoute: TeamsTeamIdTimeTeamLogsRoute,
  TeamsTeamIdTimeIndexRoute: TeamsTeamIdTimeIndexRoute,
  TeamsTeamIdTimeLogLogIdRoute: TeamsTeamIdTimeLogLogIdRoute,
  TeamsTeamIdTimeManageRatesUserIdRoute: TeamsTeamIdTimeManageRatesUserIdRoute,
  TeamsTeamIdTimeManageRatesIndexRoute: TeamsTeamIdTimeManageRatesIndexRoute,
}

const TeamsTeamIdTimeRouteRouteWithChildren =
  TeamsTeamIdTimeRouteRoute._addFileChildren(TeamsTeamIdTimeRouteRouteChildren)

interface TeamsTeamIdRouteChildren {
  TeamsTeamIdTimeRouteRoute: typeof TeamsTeamIdTimeRouteRouteWithChildren
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  TeamsTeamIdSettingsGeneralRoute: typeof TeamsTeamIdSettingsGeneralRoute
  TeamsTeamIdSettingsLogsRoute: typeof TeamsTeamIdSettingsLogsRoute
  TeamsTeamIdSettingsProjectsRoute: typeof TeamsTeamIdSettingsProjectsRoute
  TeamsTeamIdSettingsTimeRoute: typeof TeamsTeamIdSettingsTimeRoute
  TeamsTeamIdSettingsIndexRoute: typeof TeamsTeamIdSettingsIndexRoute
}

const TeamsTeamIdRouteChildren: TeamsTeamIdRouteChildren = {
  TeamsTeamIdTimeRouteRoute: TeamsTeamIdTimeRouteRouteWithChildren,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  TeamsTeamIdSettingsGeneralRoute: TeamsTeamIdSettingsGeneralRoute,
  TeamsTeamIdSettingsLogsRoute: TeamsTeamIdSettingsLogsRoute,
  TeamsTeamIdSettingsProjectsRoute: TeamsTeamIdSettingsProjectsRoute,
  TeamsTeamIdSettingsTimeRoute: TeamsTeamIdSettingsTimeRoute,
  TeamsTeamIdSettingsIndexRoute: TeamsTeamIdSettingsIndexRoute,
}

const TeamsTeamIdRouteWithChildren = TeamsTeamIdRoute._addFileChildren(
  TeamsTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoadmapTemplatesRouteRoute: RoadmapTemplatesRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CommandCenterRoute: CommandCenterRoute,
  DashboardRoute: DashboardRoute,
  InboxRoute: InboxRoute,
  MeetingsRoute: MeetingsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectPostingRoute: ProjectPostingRoute,
  WelcomeRoute: WelcomeRoute,
  WorkItemsRoute: WorkItemsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ConsultantProfileIdRoute: ConsultantProfileIdRoute,
  ConsultantApplyRoute: ConsultantApplyRoute,
  ConsultantBrowseRoute: ConsultantBrowseRoute,
  ConsultantMarketplaceRoute: ConsultantMarketplaceRoute,
  ConsultantTemplatesRoute: ConsultantTemplatesRoute,
  FreelancerGoLiveRoute: FreelancerGoLiveRoute,
  FreelancerInvitesRoute: FreelancerInvitesRoute,
  ProfileProfileIdRoute: ProfileProfileIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  RoadmapSharedWithMeRoute: RoadmapSharedWithMeRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  TeamsTeamIdRoute: TeamsTeamIdRouteWithChildren,
  ConsultantIndexRoute: ConsultantIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthAdminSigninRoute: AuthAdminSigninRoute,
  RoadmapSharedTokenRoute: RoadmapSharedTokenRoute,
  TeamsMeInvitesRoute: TeamsMeInvitesRoute,
  ProjectRoadmapIndexRoute: ProjectRoadmapIndexRoute,
  ProjectRoadmapConvertRoadmapIdRoute: ProjectRoadmapConvertRoadmapIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
