/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectPostingRouteImport } from './routes/project-posting'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoadmapSharedWithMeRouteImport } from './routes/roadmap/shared-with-me'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ProfileProfileIdRouteImport } from './routes/profile/$profileId'
import { Route as FreelancerInvitesRouteImport } from './routes/freelancer/invites'
import { Route as FreelancerGoLiveRouteImport } from './routes/freelancer/go-live'
import { Route as ConsultantTemplatesRouteImport } from './routes/consultant/templates'
import { Route as ConsultantMarketplaceRouteImport } from './routes/consultant/marketplace'
import { Route as ConsultantBrowseRouteImport } from './routes/consultant/browse'
import { Route as ConsultantApplyRouteImport } from './routes/consultant/apply'
import { Route as ConsultantProfileIdRouteImport } from './routes/consultant/$profileId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMatchRouteImport } from './routes/admin/match'
import { Route as AdminApproveAdminRouteImport } from './routes/admin/approve-admin'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as ProjectRoadmapIndexRouteImport } from './routes/project/roadmap/index'
import { Route as RoadmapSharedTokenRouteImport } from './routes/roadmap/shared/$token'
import { Route as ProjectProjectIdWorkItemsRouteImport } from './routes/project/$projectId/work-items'
import { Route as ProjectProjectIdTeamRouteImport } from './routes/project/$projectId/team'
import { Route as ProjectProjectIdRoadmapRouteImport } from './routes/project/$projectId/roadmap'
import { Route as ProjectProjectIdResourcesRouteImport } from './routes/project/$projectId/resources'
import { Route as ProjectProjectIdPaymentsRouteImport } from './routes/project/$projectId/payments'
import { Route as ProjectProjectIdOverviewRouteImport } from './routes/project/$projectId/overview'
import { Route as ProjectProjectIdLogsRouteImport } from './routes/project/$projectId/logs'
import { Route as AuthAdminSigninRouteImport } from './routes/auth/admin/signin'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'
import { Route as ProjectProjectIdTimeIndexRouteImport } from './routes/project/$projectId/time/index'
import { Route as ProjectProjectIdSettingsIndexRouteImport } from './routes/project/$projectId/settings/index'
import { Route as ProjectProjectIdWorkItemsRoadmapIdRouteImport } from './routes/project/$projectId/work-items/$roadmapId'
import { Route as ProjectProjectIdTimeTeamLogsRouteImport } from './routes/project/$projectId/time/team-logs'
import { Route as ProjectProjectIdTimeMyLogsRouteImport } from './routes/project/$projectId/time/my-logs'
import { Route as ProjectProjectIdSettingsTeamRouteImport } from './routes/project/$projectId/settings/team'
import { Route as ProjectProjectIdSettingsGeneralRouteImport } from './routes/project/$projectId/settings/general'
import { Route as ProjectProjectIdRoadmapCreateRouteImport } from './routes/project/$projectId/roadmap/create'
import { Route as ProjectProjectIdRoadmapRoadmapIdRouteImport } from './routes/project/$projectId/roadmap/$roadmapId'
import { Route as ProjectProjectIdChatChatRefRouteImport } from './routes/project/$projectId/chat/$chatRef'
import { Route as ProjectProjectIdTimeTeamLogsProjectMemberIdRouteImport } from './routes/project/$projectId/time/team-logs/$projectMemberId'

const ProjectPostingRoute = ProjectPostingRouteImport.update({
  id: '/project-posting',
  path: '/project-posting',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RoadmapSharedWithMeRoute = RoadmapSharedWithMeRouteImport.update({
  id: '/roadmap/shared-with-me',
  path: '/roadmap/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerInvitesRoute = FreelancerInvitesRouteImport.update({
  id: '/freelancer/invites',
  path: '/freelancer/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerGoLiveRoute = FreelancerGoLiveRouteImport.update({
  id: '/freelancer/go-live',
  path: '/freelancer/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantTemplatesRoute = ConsultantTemplatesRouteImport.update({
  id: '/consultant/templates',
  path: '/consultant/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantMarketplaceRoute = ConsultantMarketplaceRouteImport.update({
  id: '/consultant/marketplace',
  path: '/consultant/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantBrowseRoute = ConsultantBrowseRouteImport.update({
  id: '/consultant/browse',
  path: '/consultant/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantApplyRoute = ConsultantApplyRouteImport.update({
  id: '/consultant/apply',
  path: '/consultant/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantProfileIdRoute = ConsultantProfileIdRouteImport.update({
  id: '/consultant/$profileId',
  path: '/consultant/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchRoute = AdminMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApproveAdminRoute = AdminApproveAdminRouteImport.update({
  id: '/approve-admin',
  path: '/approve-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectRoadmapIndexRoute = ProjectRoadmapIndexRouteImport.update({
  id: '/project/roadmap/',
  path: '/project/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapSharedTokenRoute = RoadmapSharedTokenRouteImport.update({
  id: '/roadmap/shared/$token',
  path: '/roadmap/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdWorkItemsRoute =
  ProjectProjectIdWorkItemsRouteImport.update({
    id: '/work-items',
    path: '/work-items',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTeamRoute = ProjectProjectIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdRoadmapRoute = ProjectProjectIdRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdResourcesRoute =
  ProjectProjectIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdPaymentsRoute =
  ProjectProjectIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdOverviewRoute =
  ProjectProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdLogsRoute = ProjectProjectIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const AuthAdminSigninRoute = AuthAdminSigninRouteImport.update({
  id: '/auth/admin/signin',
  path: '/auth/admin/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdTimeIndexRoute =
  ProjectProjectIdTimeIndexRouteImport.update({
    id: '/time/',
    path: '/time/',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsIndexRoute =
  ProjectProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdWorkItemsRoadmapIdRoute =
  ProjectProjectIdWorkItemsRoadmapIdRouteImport.update({
    id: '/$roadmapId',
    path: '/$roadmapId',
    getParentRoute: () => ProjectProjectIdWorkItemsRoute,
  } as any)
const ProjectProjectIdTimeTeamLogsRoute =
  ProjectProjectIdTimeTeamLogsRouteImport.update({
    id: '/time/team-logs',
    path: '/time/team-logs',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTimeMyLogsRoute =
  ProjectProjectIdTimeMyLogsRouteImport.update({
    id: '/time/my-logs',
    path: '/time/my-logs',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsTeamRoute =
  ProjectProjectIdSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSettingsGeneralRoute =
  ProjectProjectIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdRoadmapCreateRoute =
  ProjectProjectIdRoadmapCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ProjectProjectIdRoadmapRoute,
  } as any)
const ProjectProjectIdRoadmapRoadmapIdRoute =
  ProjectProjectIdRoadmapRoadmapIdRouteImport.update({
    id: '/$roadmapId',
    path: '/$roadmapId',
    getParentRoute: () => ProjectProjectIdRoadmapRoute,
  } as any)
const ProjectProjectIdChatChatRefRoute =
  ProjectProjectIdChatChatRefRouteImport.update({
    id: '/chat/$chatRef',
    path: '/chat/$chatRef',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTimeTeamLogsProjectMemberIdRoute =
  ProjectProjectIdTimeTeamLogsProjectMemberIdRouteImport.update({
    id: '/$projectMemberId',
    path: '/$projectMemberId',
    getParentRoute: () => ProjectProjectIdTimeTeamLogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/project-posting': typeof ProjectPostingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/consultant/marketplace': typeof ConsultantMarketplaceRoute
  '/consultant/templates': typeof ConsultantTemplatesRoute
  '/freelancer/go-live': typeof FreelancerGoLiveRoute
  '/freelancer/invites': typeof FreelancerInvitesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/logs': typeof ProjectProjectIdLogsRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/resources': typeof ProjectProjectIdResourcesRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/team': typeof ProjectProjectIdTeamRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRouteWithChildren
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/project/roadmap': typeof ProjectRoadmapIndexRoute
  '/project/$projectId/chat/$chatRef': typeof ProjectProjectIdChatChatRefRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
  '/project/$projectId/roadmap/create': typeof ProjectProjectIdRoadmapCreateRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/team': typeof ProjectProjectIdSettingsTeamRoute
  '/project/$projectId/time/my-logs': typeof ProjectProjectIdTimeMyLogsRoute
  '/project/$projectId/time/team-logs': typeof ProjectProjectIdTimeTeamLogsRouteWithChildren
  '/project/$projectId/work-items/$roadmapId': typeof ProjectProjectIdWorkItemsRoadmapIdRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsIndexRoute
  '/project/$projectId/time': typeof ProjectProjectIdTimeIndexRoute
  '/project/$projectId/time/team-logs/$projectMemberId': typeof ProjectProjectIdTimeTeamLogsProjectMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/project-posting': typeof ProjectPostingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/consultant/marketplace': typeof ConsultantMarketplaceRoute
  '/consultant/templates': typeof ConsultantTemplatesRoute
  '/freelancer/go-live': typeof FreelancerGoLiveRoute
  '/freelancer/invites': typeof FreelancerInvitesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/admin': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/logs': typeof ProjectProjectIdLogsRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/resources': typeof ProjectProjectIdResourcesRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/team': typeof ProjectProjectIdTeamRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRouteWithChildren
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/project/roadmap': typeof ProjectRoadmapIndexRoute
  '/project/$projectId/chat/$chatRef': typeof ProjectProjectIdChatChatRefRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
  '/project/$projectId/roadmap/create': typeof ProjectProjectIdRoadmapCreateRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/team': typeof ProjectProjectIdSettingsTeamRoute
  '/project/$projectId/time/my-logs': typeof ProjectProjectIdTimeMyLogsRoute
  '/project/$projectId/time/team-logs': typeof ProjectProjectIdTimeTeamLogsRouteWithChildren
  '/project/$projectId/work-items/$roadmapId': typeof ProjectProjectIdWorkItemsRoadmapIdRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsIndexRoute
  '/project/$projectId/time': typeof ProjectProjectIdTimeIndexRoute
  '/project/$projectId/time/team-logs/$projectMemberId': typeof ProjectProjectIdTimeTeamLogsProjectMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/project-posting': typeof ProjectPostingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/consultant/marketplace': typeof ConsultantMarketplaceRoute
  '/consultant/templates': typeof ConsultantTemplatesRoute
  '/freelancer/go-live': typeof FreelancerGoLiveRoute
  '/freelancer/invites': typeof FreelancerInvitesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/logs': typeof ProjectProjectIdLogsRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/resources': typeof ProjectProjectIdResourcesRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/team': typeof ProjectProjectIdTeamRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRouteWithChildren
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/project/roadmap/': typeof ProjectRoadmapIndexRoute
  '/project/$projectId/chat/$chatRef': typeof ProjectProjectIdChatChatRefRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
  '/project/$projectId/roadmap/create': typeof ProjectProjectIdRoadmapCreateRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/team': typeof ProjectProjectIdSettingsTeamRoute
  '/project/$projectId/time/my-logs': typeof ProjectProjectIdTimeMyLogsRoute
  '/project/$projectId/time/team-logs': typeof ProjectProjectIdTimeTeamLogsRouteWithChildren
  '/project/$projectId/work-items/$roadmapId': typeof ProjectProjectIdWorkItemsRoadmapIdRoute
  '/project/$projectId/settings/': typeof ProjectProjectIdSettingsIndexRoute
  '/project/$projectId/time/': typeof ProjectProjectIdTimeIndexRoute
  '/project/$projectId/time/team-logs/$projectMemberId': typeof ProjectProjectIdTimeTeamLogsProjectMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/landing'
    | '/notifications'
    | '/onboarding'
    | '/project-posting'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/consultant/marketplace'
    | '/consultant/templates'
    | '/freelancer/go-live'
    | '/freelancer/invites'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap/shared-with-me'
    | '/admin/'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/logs'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/resources'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/team'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/project/roadmap'
    | '/project/$projectId/chat/$chatRef'
    | '/project/$projectId/roadmap/$roadmapId'
    | '/project/$projectId/roadmap/create'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/team'
    | '/project/$projectId/time/my-logs'
    | '/project/$projectId/time/team-logs'
    | '/project/$projectId/work-items/$roadmapId'
    | '/project/$projectId/settings'
    | '/project/$projectId/time'
    | '/project/$projectId/time/team-logs/$projectMemberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/notifications'
    | '/onboarding'
    | '/project-posting'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/consultant/marketplace'
    | '/consultant/templates'
    | '/freelancer/go-live'
    | '/freelancer/invites'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap/shared-with-me'
    | '/admin'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/logs'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/resources'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/team'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/project/roadmap'
    | '/project/$projectId/chat/$chatRef'
    | '/project/$projectId/roadmap/$roadmapId'
    | '/project/$projectId/roadmap/create'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/team'
    | '/project/$projectId/time/my-logs'
    | '/project/$projectId/time/team-logs'
    | '/project/$projectId/work-items/$roadmapId'
    | '/project/$projectId/settings'
    | '/project/$projectId/time'
    | '/project/$projectId/time/team-logs/$projectMemberId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/landing'
    | '/notifications'
    | '/onboarding'
    | '/project-posting'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/consultant/marketplace'
    | '/consultant/templates'
    | '/freelancer/go-live'
    | '/freelancer/invites'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap/shared-with-me'
    | '/admin/'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/logs'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/resources'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/team'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/project/roadmap/'
    | '/project/$projectId/chat/$chatRef'
    | '/project/$projectId/roadmap/$roadmapId'
    | '/project/$projectId/roadmap/create'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/team'
    | '/project/$projectId/time/my-logs'
    | '/project/$projectId/time/team-logs'
    | '/project/$projectId/work-items/$roadmapId'
    | '/project/$projectId/settings/'
    | '/project/$projectId/time/'
    | '/project/$projectId/time/team-logs/$projectMemberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectPostingRoute: typeof ProjectPostingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ConsultantProfileIdRoute: typeof ConsultantProfileIdRoute
  ConsultantApplyRoute: typeof ConsultantApplyRoute
  ConsultantBrowseRoute: typeof ConsultantBrowseRoute
  ConsultantMarketplaceRoute: typeof ConsultantMarketplaceRoute
  ConsultantTemplatesRoute: typeof ConsultantTemplatesRoute
  FreelancerGoLiveRoute: typeof FreelancerGoLiveRoute
  FreelancerInvitesRoute: typeof FreelancerInvitesRoute
  ProfileProfileIdRoute: typeof ProfileProfileIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  RoadmapSharedWithMeRoute: typeof RoadmapSharedWithMeRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthAdminSigninRoute: typeof AuthAdminSigninRoute
  RoadmapSharedTokenRoute: typeof RoadmapSharedTokenRoute
  ProjectRoadmapIndexRoute: typeof ProjectRoadmapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-posting': {
      id: '/project-posting'
      path: '/project-posting'
      fullPath: '/project-posting'
      preLoaderRoute: typeof ProjectPostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/roadmap/shared-with-me': {
      id: '/roadmap/shared-with-me'
      path: '/roadmap/shared-with-me'
      fullPath: '/roadmap/shared-with-me'
      preLoaderRoute: typeof RoadmapSharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/invites': {
      id: '/freelancer/invites'
      path: '/freelancer/invites'
      fullPath: '/freelancer/invites'
      preLoaderRoute: typeof FreelancerInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/go-live': {
      id: '/freelancer/go-live'
      path: '/freelancer/go-live'
      fullPath: '/freelancer/go-live'
      preLoaderRoute: typeof FreelancerGoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/templates': {
      id: '/consultant/templates'
      path: '/consultant/templates'
      fullPath: '/consultant/templates'
      preLoaderRoute: typeof ConsultantTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/marketplace': {
      id: '/consultant/marketplace'
      path: '/consultant/marketplace'
      fullPath: '/consultant/marketplace'
      preLoaderRoute: typeof ConsultantMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/browse': {
      id: '/consultant/browse'
      path: '/consultant/browse'
      fullPath: '/consultant/browse'
      preLoaderRoute: typeof ConsultantBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/apply': {
      id: '/consultant/apply'
      path: '/consultant/apply'
      fullPath: '/consultant/apply'
      preLoaderRoute: typeof ConsultantApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/$profileId': {
      id: '/consultant/$profileId'
      path: '/consultant/$profileId'
      fullPath: '/consultant/$profileId'
      preLoaderRoute: typeof ConsultantProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/match': {
      id: '/admin/match'
      path: '/match'
      fullPath: '/admin/match'
      preLoaderRoute: typeof AdminMatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approve-admin': {
      id: '/admin/approve-admin'
      path: '/approve-admin'
      fullPath: '/admin/approve-admin'
      preLoaderRoute: typeof AdminApproveAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/roadmap/': {
      id: '/project/roadmap/'
      path: '/project/roadmap'
      fullPath: '/project/roadmap'
      preLoaderRoute: typeof ProjectRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/shared/$token': {
      id: '/roadmap/shared/$token'
      path: '/roadmap/shared/$token'
      fullPath: '/roadmap/shared/$token'
      preLoaderRoute: typeof RoadmapSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/work-items': {
      id: '/project/$projectId/work-items'
      path: '/work-items'
      fullPath: '/project/$projectId/work-items'
      preLoaderRoute: typeof ProjectProjectIdWorkItemsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/team': {
      id: '/project/$projectId/team'
      path: '/team'
      fullPath: '/project/$projectId/team'
      preLoaderRoute: typeof ProjectProjectIdTeamRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmap': {
      id: '/project/$projectId/roadmap'
      path: '/roadmap'
      fullPath: '/project/$projectId/roadmap'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/resources': {
      id: '/project/$projectId/resources'
      path: '/resources'
      fullPath: '/project/$projectId/resources'
      preLoaderRoute: typeof ProjectProjectIdResourcesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/payments': {
      id: '/project/$projectId/payments'
      path: '/payments'
      fullPath: '/project/$projectId/payments'
      preLoaderRoute: typeof ProjectProjectIdPaymentsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/overview': {
      id: '/project/$projectId/overview'
      path: '/overview'
      fullPath: '/project/$projectId/overview'
      preLoaderRoute: typeof ProjectProjectIdOverviewRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/logs': {
      id: '/project/$projectId/logs'
      path: '/logs'
      fullPath: '/project/$projectId/logs'
      preLoaderRoute: typeof ProjectProjectIdLogsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/auth/admin/signin': {
      id: '/auth/admin/signin'
      path: '/auth/admin/signin'
      fullPath: '/auth/admin/signin'
      preLoaderRoute: typeof AuthAdminSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/time/': {
      id: '/project/$projectId/time/'
      path: '/time'
      fullPath: '/project/$projectId/time'
      preLoaderRoute: typeof ProjectProjectIdTimeIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/': {
      id: '/project/$projectId/settings/'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/work-items/$roadmapId': {
      id: '/project/$projectId/work-items/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/project/$projectId/work-items/$roadmapId'
      preLoaderRoute: typeof ProjectProjectIdWorkItemsRoadmapIdRouteImport
      parentRoute: typeof ProjectProjectIdWorkItemsRoute
    }
    '/project/$projectId/time/team-logs': {
      id: '/project/$projectId/time/team-logs'
      path: '/time/team-logs'
      fullPath: '/project/$projectId/time/team-logs'
      preLoaderRoute: typeof ProjectProjectIdTimeTeamLogsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/time/my-logs': {
      id: '/project/$projectId/time/my-logs'
      path: '/time/my-logs'
      fullPath: '/project/$projectId/time/my-logs'
      preLoaderRoute: typeof ProjectProjectIdTimeMyLogsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/team': {
      id: '/project/$projectId/settings/team'
      path: '/settings/team'
      fullPath: '/project/$projectId/settings/team'
      preLoaderRoute: typeof ProjectProjectIdSettingsTeamRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/general': {
      id: '/project/$projectId/settings/general'
      path: '/settings/general'
      fullPath: '/project/$projectId/settings/general'
      preLoaderRoute: typeof ProjectProjectIdSettingsGeneralRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmap/create': {
      id: '/project/$projectId/roadmap/create'
      path: '/create'
      fullPath: '/project/$projectId/roadmap/create'
      preLoaderRoute: typeof ProjectProjectIdRoadmapCreateRouteImport
      parentRoute: typeof ProjectProjectIdRoadmapRoute
    }
    '/project/$projectId/roadmap/$roadmapId': {
      id: '/project/$projectId/roadmap/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/project/$projectId/roadmap/$roadmapId'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRoadmapIdRouteImport
      parentRoute: typeof ProjectProjectIdRoadmapRoute
    }
    '/project/$projectId/chat/$chatRef': {
      id: '/project/$projectId/chat/$chatRef'
      path: '/chat/$chatRef'
      fullPath: '/project/$projectId/chat/$chatRef'
      preLoaderRoute: typeof ProjectProjectIdChatChatRefRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/time/team-logs/$projectMemberId': {
      id: '/project/$projectId/time/team-logs/$projectMemberId'
      path: '/$projectMemberId'
      fullPath: '/project/$projectId/time/team-logs/$projectMemberId'
      preLoaderRoute: typeof ProjectProjectIdTimeTeamLogsProjectMemberIdRouteImport
      parentRoute: typeof ProjectProjectIdTimeTeamLogsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminApproveAdminRoute: typeof AdminApproveAdminRoute
  AdminMatchRoute: typeof AdminMatchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminApproveAdminRoute: AdminApproveAdminRoute,
  AdminMatchRoute: AdminMatchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectProjectIdRoadmapRouteChildren {
  ProjectProjectIdRoadmapRoadmapIdRoute: typeof ProjectProjectIdRoadmapRoadmapIdRoute
  ProjectProjectIdRoadmapCreateRoute: typeof ProjectProjectIdRoadmapCreateRoute
}

const ProjectProjectIdRoadmapRouteChildren: ProjectProjectIdRoadmapRouteChildren =
  {
    ProjectProjectIdRoadmapRoadmapIdRoute:
      ProjectProjectIdRoadmapRoadmapIdRoute,
    ProjectProjectIdRoadmapCreateRoute: ProjectProjectIdRoadmapCreateRoute,
  }

const ProjectProjectIdRoadmapRouteWithChildren =
  ProjectProjectIdRoadmapRoute._addFileChildren(
    ProjectProjectIdRoadmapRouteChildren,
  )

interface ProjectProjectIdWorkItemsRouteChildren {
  ProjectProjectIdWorkItemsRoadmapIdRoute: typeof ProjectProjectIdWorkItemsRoadmapIdRoute
}

const ProjectProjectIdWorkItemsRouteChildren: ProjectProjectIdWorkItemsRouteChildren =
  {
    ProjectProjectIdWorkItemsRoadmapIdRoute:
      ProjectProjectIdWorkItemsRoadmapIdRoute,
  }

const ProjectProjectIdWorkItemsRouteWithChildren =
  ProjectProjectIdWorkItemsRoute._addFileChildren(
    ProjectProjectIdWorkItemsRouteChildren,
  )

interface ProjectProjectIdTimeTeamLogsRouteChildren {
  ProjectProjectIdTimeTeamLogsProjectMemberIdRoute: typeof ProjectProjectIdTimeTeamLogsProjectMemberIdRoute
}

const ProjectProjectIdTimeTeamLogsRouteChildren: ProjectProjectIdTimeTeamLogsRouteChildren =
  {
    ProjectProjectIdTimeTeamLogsProjectMemberIdRoute:
      ProjectProjectIdTimeTeamLogsProjectMemberIdRoute,
  }

const ProjectProjectIdTimeTeamLogsRouteWithChildren =
  ProjectProjectIdTimeTeamLogsRoute._addFileChildren(
    ProjectProjectIdTimeTeamLogsRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdLogsRoute: typeof ProjectProjectIdLogsRoute
  ProjectProjectIdOverviewRoute: typeof ProjectProjectIdOverviewRoute
  ProjectProjectIdPaymentsRoute: typeof ProjectProjectIdPaymentsRoute
  ProjectProjectIdResourcesRoute: typeof ProjectProjectIdResourcesRoute
  ProjectProjectIdRoadmapRoute: typeof ProjectProjectIdRoadmapRouteWithChildren
  ProjectProjectIdTeamRoute: typeof ProjectProjectIdTeamRoute
  ProjectProjectIdWorkItemsRoute: typeof ProjectProjectIdWorkItemsRouteWithChildren
  ProjectProjectIdChatChatRefRoute: typeof ProjectProjectIdChatChatRefRoute
  ProjectProjectIdSettingsGeneralRoute: typeof ProjectProjectIdSettingsGeneralRoute
  ProjectProjectIdSettingsTeamRoute: typeof ProjectProjectIdSettingsTeamRoute
  ProjectProjectIdTimeMyLogsRoute: typeof ProjectProjectIdTimeMyLogsRoute
  ProjectProjectIdTimeTeamLogsRoute: typeof ProjectProjectIdTimeTeamLogsRouteWithChildren
  ProjectProjectIdSettingsIndexRoute: typeof ProjectProjectIdSettingsIndexRoute
  ProjectProjectIdTimeIndexRoute: typeof ProjectProjectIdTimeIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdLogsRoute: ProjectProjectIdLogsRoute,
  ProjectProjectIdOverviewRoute: ProjectProjectIdOverviewRoute,
  ProjectProjectIdPaymentsRoute: ProjectProjectIdPaymentsRoute,
  ProjectProjectIdResourcesRoute: ProjectProjectIdResourcesRoute,
  ProjectProjectIdRoadmapRoute: ProjectProjectIdRoadmapRouteWithChildren,
  ProjectProjectIdTeamRoute: ProjectProjectIdTeamRoute,
  ProjectProjectIdWorkItemsRoute: ProjectProjectIdWorkItemsRouteWithChildren,
  ProjectProjectIdChatChatRefRoute: ProjectProjectIdChatChatRefRoute,
  ProjectProjectIdSettingsGeneralRoute: ProjectProjectIdSettingsGeneralRoute,
  ProjectProjectIdSettingsTeamRoute: ProjectProjectIdSettingsTeamRoute,
  ProjectProjectIdTimeMyLogsRoute: ProjectProjectIdTimeMyLogsRoute,
  ProjectProjectIdTimeTeamLogsRoute:
    ProjectProjectIdTimeTeamLogsRouteWithChildren,
  ProjectProjectIdSettingsIndexRoute: ProjectProjectIdSettingsIndexRoute,
  ProjectProjectIdTimeIndexRoute: ProjectProjectIdTimeIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectPostingRoute: ProjectPostingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ConsultantProfileIdRoute: ConsultantProfileIdRoute,
  ConsultantApplyRoute: ConsultantApplyRoute,
  ConsultantBrowseRoute: ConsultantBrowseRoute,
  ConsultantMarketplaceRoute: ConsultantMarketplaceRoute,
  ConsultantTemplatesRoute: ConsultantTemplatesRoute,
  FreelancerGoLiveRoute: FreelancerGoLiveRoute,
  FreelancerInvitesRoute: FreelancerInvitesRoute,
  ProfileProfileIdRoute: ProfileProfileIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  RoadmapSharedWithMeRoute: RoadmapSharedWithMeRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthAdminSigninRoute: AuthAdminSigninRoute,
  RoadmapSharedTokenRoute: RoadmapSharedTokenRoute,
  ProjectRoadmapIndexRoute: ProjectRoadmapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
