import { FileText, Loader2, UploadCloud, X } from "lucide-react";
import { useRef, useState } from "react";
import type {
	IdentityDocumentType,
	UserIdentityDocument,
} from "@/services/profile.service";
import { ProfileModal } from "./ProfileModal";

type DocumentPayload = Omit<
	UserIdentityDocument,
	| "id"
	| "user_id"
	| "is_verified"
	| "verified_at"
	| "verified_by"
	| "uploaded_at"
	| "created_at"
	| "updated_at"
>;

interface Props {
	isOpen: boolean;
	onClose: () => void;
	onSave: (payload: DocumentPayload, file: File) => void;
	isSaving?: boolean;
}

const DOC_TYPES: { value: IdentityDocumentType; label: string }[] = [
	{ value: "passport", label: "Passport" },
	{ value: "national_id", label: "National ID Card" },
	{ value: "drivers_license", label: "Driver's License" },
	{ value: "other", label: "Other Official Document" },
];

export function IdentityDocumentModal({
	isOpen,
	onClose,
	onSave,
	isSaving,
}: Props) {
	const [type, setType] = useState<IdentityDocumentType>("national_id");
	const [file, setFile] = useState<File | null>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		if (!type || !file) return;

		// For simplicity locally, we just mock the 'storage_path' here.
		// The actual path will be generated by the uploadService right before inserting to the DB.
		// The component caller will handle the upload and the DB insertion.
		onSave({ type, storage_path: "" }, file);
	};

	const handleDragOver = (e: React.DragEvent) => {
		e.preventDefault();
	};

	const handleDrop = (e: React.DragEvent) => {
		e.preventDefault();
		if (e.dataTransfer.files && e.dataTransfer.files[0]) {
			setFile(e.dataTransfer.files[0]);
		}
	};

	return (
		<ProfileModal
			isOpen={isOpen}
			onClose={onClose}
			title="Upload Verification Document"
			width="md"
		>
			<form onSubmit={handleSubmit} className="space-y-5">
				<div className="space-y-1.5">
					<label className="text-sm font-semibold text-gray-900">
						Document Type
					</label>
					<select
						value={type}
						onChange={(e) => setType(e.target.value as IdentityDocumentType)}
						className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-[#ff9933] focus:border-transparent outline-none bg-white"
					>
						{DOC_TYPES.map((t) => (
							<option key={t.value} value={t.value}>
								{t.label}
							</option>
						))}
					</select>
					<p className="text-xs text-gray-500 mt-1">
						We will use this document to verify your identity. It will only be
						visible to our administration team.
					</p>
				</div>

				<div className="space-y-2">
					<label className="text-sm font-semibold text-gray-900">
						Upload File
					</label>
					{!file ? (
						<div
							className="border-2 border-dashed border-gray-300 rounded-xl p-8 hover:bg-gray-50 hover:border-[#ff9933] transition-colors cursor-pointer text-center"
							onClick={() => fileInputRef.current?.click()}
							onDragOver={handleDragOver}
							onDrop={handleDrop}
						>
							<UploadCloud className="w-8 h-8 text-[#ff9933] mx-auto mb-3" />
							<p className="text-sm font-semibold text-gray-900 mb-1">
								Click to upload or drag and drop
							</p>
							<p className="text-xs text-gray-500">
								PNG, JPG, or PDF (max. 10MB)
							</p>
						</div>
					) : (
						<div className="flex items-center justify-between p-3 border border-gray-200 rounded-lg bg-gray-50">
							<div className="flex items-center gap-3 overflow-hidden">
								<div className="w-10 h-10 rounded-lg bg-[#ff9933]/10 flex items-center justify-center shrink-0">
									<FileText className="w-5 h-5 text-[#ff9933]" />
								</div>
								<div className="flex-1 min-w-0">
									<p className="text-sm font-semibold text-gray-900 truncate">
										{file.name}
									</p>
									<p className="text-xs text-gray-500">
										{(file.size / 1024 / 1024).toFixed(2)} MB
									</p>
								</div>
							</div>
							<button
								type="button"
								onClick={() => setFile(null)}
								className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors shrink-0"
							>
								<X className="w-4 h-4" />
							</button>
						</div>
					)}
					<input
						type="file"
						ref={fileInputRef}
						className="hidden"
						accept="image/jpeg,image/png,image/webp,application/pdf"
						onChange={(e) => {
							if (e.target.files && e.target.files[0])
								setFile(e.target.files[0]);
						}}
					/>
				</div>

				<div className="bg-blue-50 text-blue-800 p-3 rounded-lg text-xs leading-relaxed">
					<strong>Privacy Note:</strong> Uploaded documents are securely
					encrypted and stored in private buckets. They are strictly used for
					KYC (Know Your Customer) verifications.
				</div>

				<div className="pt-4 flex justify-end gap-3 border-t border-gray-100">
					<button
						type="button"
						onClick={onClose}
						disabled={isSaving}
						className="px-5 py-2 text-sm font-medium text-[#14b8a6] hover:bg-teal-50 rounded-full transition-colors"
					>
						Cancel
					</button>
					<button
						type="submit"
						disabled={isSaving || !file}
						className="flex items-center gap-2 px-5 py-2 bg-gray-100 text-gray-400 text-sm font-medium rounded-full hover:bg-[#ff9933] hover:text-white disabled:opacity-50 disabled:hover:bg-gray-100 disabled:hover:text-gray-400 transition-colors"
					>
						{isSaving && <Loader2 className="w-4 h-4 animate-spin" />}
						Upload Now
					</button>
				</div>
			</form>
		</ProfileModal>
	);
}
